### ISSUE TITLE
Documentation/lkl.txt isn't quite Markdown syntax

### ISSUE THREAD

**Issue by cemeyer** [lkl/linux#10]
Feel free to ignore or close this one — I realize the README.md symlink is mostly a convenience for Github users and will never go upstream, while `Documentation/lkl.txt` may well land in Linus' tree.

However, some of lkl.txt renders ugly in Github Markdown.  Individual lines that should be left unformatted (code / shell examples) get merged (in the "Building" sections).

**Comment by tavip** [comment]
Ah, didn't noticed that. The other option would be to replace the existing Linux kernel README with a link to Documentation/lkl.txt but initially I felt like I should not touch that.

Any other options? Can we tell GitHUB to use another file instead of README?

**Comment by cemeyer** [comment]
I believe we could just indent code blocks in lkl.txt by 4 spaces, and that should render OK.  And it may still be acceptable for Documentation/*.txt.

> Standard Markdown converts text with four spaces at the beginning of each line into a code block; GFM also supports fenced blocks. Just wrap your code in ``` (as shown below) and you won't need to indent it by four spaces. … Keep in mind that, within lists, you must indent non-fenced code blocks eight spaces to render them properly.

**Comment by tavip** [comment]
Yes, indent sounds nice. Fixed in commit 3024076a1464dd096db2f6523aba79ad624fb2ac.

**Comment by cemeyer** [comment]
Looks good.
