### ISSUE TITLE
fd_get_capacity() fails to detect file size of large files on 32bit platforms.

### ISSUE THREAD

**Issue by ngkaho1234** [lkl/linux#100]
It is due to _FILE_OFFSET_BITS=64 not being set when building liblkl.

My temporary solution is to add -D_FILE_OFFSET_BITS=64 to CFLAGS.

**Comment by ngkaho1234** [comment]
https://github.com/ngkaho1234/linux/commit/d0507d4966d7c0c4aff64db9dd524bd72faab76d

If the temporary fix looks fine, i may open a pull request for it.

**Comment by opurdila** [comment]
I believe adding "CFLAGS_posix-host.o += -D_FILE_OFFSET_BITS=64" to tools/lkl/lib/Build should work as well, could you give it a try? And of course a PR to fix it is more then welcomed :) Thank you!

**Comment by ngkaho1234** [comment]
Thanks for pointing that out. Now it works flawlessly. :-) I am going to make a PR for that.

**Comment by ngkaho1234** [comment]
#101
