### ISSUE TITLE
Target for defconfig boot time?

### ISSUE THREAD

**Issue by phhusson** [lkl/linux#103]
Is there a target for boot time of defconfig's kernel?
The kernel can boot in 16ms on my computer by disabling btrfs .
Enabling btrfs make it go to >500ms, because of RAID6 and XOR benchmarking
I think that defconfig should be as fast as possible.
I understand that cptofs/fs2tar are currently main examples of LKL so the choice is not easy.

I see three options:
- leave as-is
- fix/workaround raid6 benchmark (I can't see any way to force an option on raid6)
- have multiple defconfig

For XOR benchmark, we can set XOR_SELECT_TEMPLATE in asm/xor.h

Any recommendation?

**Comment by pscollins** [comment]
I agree, personally, the raid6 setup is *very* slow; better to have a fast default startup and let users turn it back on if they need it. Maybe add a section to the README of "config flags known to work well with LKL" or something like that.

**Comment by opurdila** [comment]
I think the best option is to implement module support in LKL. Closing and referencing #63, please reopen if you think we have a better solution.
