### ISSUE TITLE
patched mingw binutils?

### ISSUE THREAD

**Issue by staalmannen** [lkl/linux#105]
Dear all, 

Is there a patched source tarball or git branch somewhere available where the "Weak NT externals" patch has been applied already in order to build lkl with MinGW?

I always get errors when I try to apply the patches (perhaps formatting issues from copying from browser, perhaps wrong target binutils source....)

**Comment by ngkaho1234** [comment]
Hello. You may trim out all the ChangeLog changes in the three patches.

**Comment by staalmannen** [comment]
Thanks! This seems to work (building atm)

**Comment by staalmannen** [comment]
I just got a linking issue after building with MinGW with the patched binutils:

`
  LD       lib/lkl-in.o
  LINK     liblkl.dll
  AR       liblkl.a
/usr/lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): In function `main':
/build/mingw-w64-crt/src/mingw-w64-v4.0.5/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2: error: ld returned 1 exit status
Makefile:113: recipe for target 'liblkl.dll' failed
make: *** [liblkl.dll] Error 1
`

**Comment by ngkaho1234** [comment]
http://filebin.ca/2Ye1zfSVz4L2/patch1
http://filebin.ca/2Ye2H9TouSpc/patch2
http://filebin.ca/2Ye2Shhy5kNf/patch3

I have uploaded the patches i use.

**Comment by ngkaho1234** [comment]
I rebuild binutils-2.26 with these patches.

**Comment by opurdila** [comment]
This is strange. Can you please check with the binaries stored in git to make sure its not a local problem?

Also, what is your host environment?

**Comment by staalmannen** [comment]
I also thought it looked strange,because a library should not contain a main() function.

My host environment is 64-bit Arch linux. I have packaged  the following packages for building lkl on AUR:

for GCC on Linux
https://aur.archlinux.org/packages/lkl-linux-git/

for MinGW:
https://aur.archlinux.org/packages/mingw-w64-binutils-weak/
https://aur.archlinux.org/packages/mingw-w64-lkl-linux-git/

Right now I am "playing" with compiling lkl natively under Windows in a VM (using msys2)
but still just trying to set it up (getting the patched binutils to build etc).

**Comment by ngkaho1234** [comment]
On windows you may need to turn on case-insensitive feature.

**Comment by staalmannen** [comment]
Msys2 just accepted a pull request for the weak externals patches  for binutils!

https://github.com/Alexpux/MSYS2-packages/commit/570ba5e019db1a82d7c396f92284266ed19a5126

so from now on (or when the build server updates the binary packages), one should be able to install the binutils binary in msys2 and compile lkl out-of-the-box :)

**Comment by opurdila** [comment]
Nice work !
