### ISSUE TITLE
lkl_syscall() passes corrupted parameter to sys_xxx()

### ISSUE THREAD

**Issue by ngkaho1234** [lkl/linux#117]
On non-64bit platforms, passing 64bit parameters will lead to parameter corruptions.
						         long params[6] = { __MAP(x, __SC_LONG, __VA_ARGS__) };  (That code on 32bit platform will likely pass garbage to the corresponding syscall routine that ingest long long parameter, while the higher part of the value is very likely to be dropped.)

I managed to solve the problem <https://github.com/ngkaho1234/linux/commit/7b655e497ada935d23a8ce8508e91b3ae1919095> , albeit the implementation doesn't look neat and tidy.

**Comment by ngkaho1234** [comment]
Hopefully other people may come up with a better method to fix the bug.

**Comment by opurdila** [comment]
One option is to do something similar to arch/x86/ia32/sys_ia32.c  I'll give it more thought.

**Comment by ngkaho1234** [comment]
@opurdila Hello. I have made some changes base on that idea. You may want to take a look at https://github.com/ngkaho1234/linux/commit/50cd5154624e89c995a1c99ea4d545d45ccec989. That method is portable to platforms other than x86(-64).

**Comment by ngkaho1234** [comment]
@opurdila just did some cleanups. If everything looks fine, i will start a PR.

**Comment by opurdila** [comment]
@ngkaho1234 It looks very promising. Just finished reviewing the full patch and left some comments. Thank you for working on this !
