### ISSUE TITLE
Client-Server program is not working when both sides are using LKL.

### ISSUE THREAD

**Issue by subhrajitbiswal** [lkl/linux#133]
Client-Server program is not working when both sides are using LKL. But its working when only one side is LKL. Please find the logs for working case (only client side is using LKL here) below.

Steps to reproduce the issue:
=======================
I have 2 simple program. one is server (it will read the input file and send it to port 9600) and one is client (it will connect to the server by giving the IP as input , read it and print the statistics). in my setup server is running in 172.27.10.29 and client is in 172.27.10.24.

I created the TAP interface (lkl_ptt0) and created a bridge br-lkl. Added TAP interface and my physical interface(eth12) to this bridge.

Server log:
=========
hadmin@VFSR2:~$ ./tcpfs ccnd.c
End of file
Total bytes sent = {192135}

client log:
======= 
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin# LKL_HIJACK_NET_TAP=lkl_ptt0 LKL_HIJACK_NET_IP=172.27.10.2 LKL_HIJACK_NET_NETMASK_LEN=24 ./lkl-hijack.sh ./tcpfc 172.27.10.29
Start time = {16:00:02:765}
Total Bytes received 192135
End time = {16:00:02:792}
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin#

server code:
========= 
```
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>

int main(int argc, char** argv)
{
    int listenfd = 0;
    int connfd = 0;
    struct sockaddr_in serv_addr;
    char sendBuff[1025];
    int numrv;
    int totalbyteswritten = 0;
    int byteswritten = 0;

    listenfd = socket(AF_INET, SOCK_STREAM, 0);

    memset(&serv_addr, '0', sizeof(serv_addr));
    memset(sendBuff, '0', sizeof(sendBuff));

    serv_addr.sin_family = AF_INET;
    serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    serv_addr.sin_port = htons(9600);

    bind(listenfd, (struct sockaddr*)&serv_addr,sizeof(serv_addr));

    if(listen(listenfd, 10) == -1)
    {
        printf("Failed to listen\n");
        return -1;
    }
    while(1)
    {
        connfd = accept(listenfd, (struct sockaddr*)NULL ,NULL);

        FILE *fp = fopen(argv[1],"rb");
        if(fp==NULL)
        {
            printf("File opern error");
            return 1;
        }

        while(1)
        {
            unsigned char buff[256]={0};
            int nread = fread(buff,1,256,fp);

            if(nread > 0)
            {
                byteswritten = write(connfd, buff, nread);
                totalbyteswritten += byteswritten;
        //      printf("totalbyteswritten so far = {%d}\n", totalbyteswritten);
            }

            if (nread < 256)
            {
                if (feof(fp))
                    printf("End of file\n");
                if (ferror(fp))
                    printf("Error reading\n");
                break;
            }
        }
        printf("Total bytes sent = {%d}\n", totalbyteswritten);
        totalbyteswritten = 0;
        close(connfd);
        sleep(1);
    }
    return 0;
}
```

client code:
======== 
```
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <netdb.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <arpa/inet.h>
#include <time.h>

void getlogtime(char *currentTime);

int main(int argc, char** argv)
{
    int sockfd = 0;
    int bytesReceived = 0;
    char recvBuff[256];
    memset(recvBuff, '0', sizeof(recvBuff));
    struct sockaddr_in serv_addr;

    if((sockfd = socket(AF_INET, SOCK_STREAM, 0))< 0)
    {
        printf("\n Error : Could not create socket \n");
        return 1;
    }

    serv_addr.sin_family = AF_INET;
    //serv_addr.sin_port = htons(atoi(argv[2])); // port
    serv_addr.sin_port = htons(9600);
    serv_addr.sin_addr.s_addr = inet_addr(argv[1]);

    if(inet_pton(AF_INET, argv[1], &serv_addr.sin_addr)<=0)
    {
        printf("\n inet_pton error occured\n");
        return 1;
    }
    if(connect(sockfd, (struct sockaddr *)&serv_addr, sizeof(serv_addr))<0)
    {
        perror("Error : Connect Failed \n");
        return 1;
    }

    FILE *fp;
    char fname[256];
    char logtime[100];
    int totalBytesRcvd = 0;

        getlogtime(logtime);
        sprintf(fname, "rcvdfle.%s", logtime);
    fp = fopen(fname, "ab");
    if(NULL == fp)
    {
        printf("Error opening file");
        return 1;
    }

        getlogtime(logtime);
        printf("Start time = {%s}\n", logtime);
    while((bytesReceived = read(sockfd, recvBuff, 256)) > 0)
    {
        totalBytesRcvd += bytesReceived;
        // recvBuff[n] = 0;
        fwrite(recvBuff, 1,bytesReceived,fp);
        // printf("%s \n", recvBuff);
    }
      printf("Total Bytes received %d\n",totalBytesRcvd);

        getlogtime(logtime);
        printf("End time = {%s}\n", logtime);

    if(bytesReceived < 0)
    {
        printf("\n Read Error \n");
    }
    close(sockfd);

    return 0;
}

void getlogtime(char *currentTime)
{
        struct timeval curTime;
        int milli;
        time_t rawtime;
        struct tm * timeinfo;
        char buffer [80];

        gettimeofday(&curTime, NULL);
        milli = curTime.tv_usec / 1000;
        time(&rawtime);
        timeinfo = localtime(&rawtime);
        strftime(buffer, 80, "%H:%M:%S", timeinfo);
        if(currentTime)
                sprintf(currentTime, "%s:%d", buffer, milli);
        //printf("current time: %s \n", currentTime);
}
```

**Comment by pscollins** [comment]
How does it fail?

**Comment by liuyuan10** [comment]
I've done the same thing (both server & client are lkl based) but not hijacked, i.e. I'm using the lkl sockets directly. And it works for me.

Are you using only one tap? can you try having two taps and build a bridge between them?

**Comment by subhrajitbiswal** [comment]
HI Yuan Liu,

    I have one tap in server and one tap in client. Do i need 2 tap interfaces in both server and client?
Can you tell me the steps and commands how you verified it ? How you used the lkl sockets directly ?
Not hijacked means you are not using (./lkl-hijack.sh). 

  Please send me the commands and output of server and client.

**Comment by subhrajitbiswal** [comment]
Hi Patrick,

  The  logs below for one side LKL (only client). If I use both side LKL, it fails.

Thanks,
Subhrajit

**Comment by liuyuan10** [comment]
I realised you probably are running server and client on two machines.
What I did was running them on the  same machine. one tap each and bridge between the two taps. Maybe you can firstly try to see if this works for your case, i.e. running your server/client on the same machine. If it works, then it means you are using the lkl correctly.

Next, you might want to use tcpdump to see how the traffic looks like in between.

**Comment by pscollins** [comment]
I'm not totally clear what error you're getting, but if the "good side" is when you have LKL on the client and host on the server, I'd bet it's an issue with your routing tables --- you need to fiddle with the routing tables a bit to be able to get the host to see an LKL client.

When you add the TAP device (say `lkl_ptt0`) at some address (say 192.168.13.3), the host kernel decides that anything behind the TAP device must actually be on the host, so it adds a route from the host machine to 191.68.13.3 through `lo`. LKL breaks this assumption because it's not available there.

Take a look at `ip route list table all` after setting up the TAP device --- delete the routes to e.g. 196.168.13.3 that go through `lo` and add in routes that go along the right path. I've only done it with LKL-server and host-client so I'm not sure how it would need to happen for LKL on both sides.

**Comment by subhrajitbiswal** [comment]
Hi Yuan,
  Its working fine when both server and client are running in same machine with both side LKL.
i created 2 TAP interfaces and bridged them. lkl_ptt0  with ip 172.27.10.2 and lkl_ptt1 with ip 172.27.10.4.. I used the hijacking. Can u pls tell me how you did it using LKL socket directly without hijacking ?

server:
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin# LKL_HIJACK_NET_TAP=lkl_ptt0 LKL_HIJACK_NET_IP=172.27.10.2 LKL_HIJACK_NET_NETMASK_LEN=24 ./lkl-hijack.sh ./tcpfs tcpfs.c
End of file
Total bytes sent = {2312}
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin#

Client:
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin# LKL_HIJACK_NET_TAP=lkl_ptt1 LKL_HIJACK_NET_IP=172.27.10.4 LKL_HIJACK_NET_NETMASK_LEN=24 ./lkl-hijack.sh ./tcpfc 172.27.10.2
Start time = {15:14:54:238}
Total Bytes received 2312
End time = {15:14:54:240}
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin#

i want to run server and client  in different machines. Can you please tell me how can i access the tap interface of server machine from the client machine ? Any configuration required for that?

**Comment by thehajime** [comment]
> I used the hijacking. Can u pls tell me how you did it using LKL socket directly without hijacking ?

the following test program uses socket without hijacking.  hope it helps.

https://github.com/lkl/linux/blob/master/tools/lkl/tests/net-test.c

for the issue of different machines, could you collect a packet trace (e.g. tcpdump) and share it here ?

**Comment by liuyuan10** [comment]
Please refer to "test_icmp" case in the code thehajime gives. It's just replacing all sys calls (socket, open..) with lkl sys calls (lkl_sys_socket, lkl_sys_open).

In your case, the path of a packet from client to lkl server is:
client lkl virtio -> host tap -> (through bridge) host physical dev -> wire -> server host physical dev -> host tap -> server lkl virtio.

You can use tcpdump on server host physical dev and tap to see what packets are received/sent on each of them.

**Comment by subhrajitbiswal** [comment]
Thanks Yuan and Hajime, its working now for  2 different machines.
Are there any lkl sys calls for bind,listen, accept like lkl_sys_socket for socket ? Where are the definition available for lkl sys calls ?

**Comment by liuyuan10** [comment]
Take a look at tools/lkl/include/lkl/asm/syscall_defs.h. Most sys calls has a lkl counterpart by default config.

How do you make it work? It may save others a bit time

**Comment by subhrajitbiswal** [comment]
Hi Yuan,
I created one TAP interface (172.27.10.1) in server (172.27.10.27) and bridged it with physical interface .
Similarly one TAP interface (172.27.10.2) in client (172.27.10.24) and bridged it with physical interface.
I used the following  commands for client and server. it worked fine. 
May be i missed some configuration or gave some wrong ip when i tried first time.

client log:
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin# LKL_HIJACK_NET_TAP=lkl_ptt0 LKL_HIJACK_NET_IP=172.27.10.2 LKL_HIJACK_NET_NETMASK_LEN=24 ./tcpfc 172.27.10.27
Start time = {14:17:58:106}
Total Bytes received 1806
End time = {14:17:58:125}
root@ICSCHELAP0027:/home/hadmin/linux/tools/lkl/bin#

Server log:
root@ICSCHELAP1003:/home/hadmin/Mari/linux/tools/lkl/bin# LKL_HIJACK_NET_TAP=lkl_ptt0 LKL_HIJACK_NET_IP=172.27.10.1 LKL_HIJACK_NET_NETMASK_LEN=24 ./tcpfs tcpfs.c
End of file
Total bytes sent = {1806}
End of file
Total bytes sent = {1806}
^C
root@ICSCHELAP1003:/home/hadmin/Mari/linux/tools/lkl/bin#

**Comment by opurdila** [comment]
Great, it seemed it was a configuration issue, so it looks like I can close this issue now.
