### ISSUE TITLE
Host cleanup infrastructure

### ISSUE THREAD

**Issue by opurdila** [lkl/linux#139]
We need a mechanism that allows the host to register cleanup functions to be called at the moment the kernel is shutdown. One example is the cleanup we need to do for net virtio, where currently we use an external function reference.

**Comment by pscollins** [comment]
I was thinking something similar while writing #135. One thing to consider, though --- how many things will we need to clean up? I can't think of anything other than `virtio_net` devices and `virtio_blk` devices, and this seems like a big change for the sake of those two functions.

**Comment by opurdila** [comment]
Closing this as the net virtio cleanup issue has been fixed by 342c0e835755ee5222602f31bf8c368574539cb3 and I no longer see a use-case for it.
