### ISSUE TITLE
At most 64 host threads calling lkl syscalls

### ISSUE THREAD

**Issue by liuyuan10** [lkl/linux#147]
In arch/lkl/include/asm/irq.h, number of irqs are set to 64.
# define NR_IRQS         ((int)sizeof(long) \* 8)

Each host thread calling lkl syscall will create a new syscall thread, which occupies one irq. So at most 64 host threads calling lkl syscalls are supported. Actually virtio and others take some irq too.

This may be a problem if user often creates and destroys new threads. For example, a server that creates a new thread for each connection.

lkl_stop_syscall_thread may be called before destroying host threads to free the irq. but the 64 hard limit is still there.

Filing this issue to keep a record and looking for possible solution.

**Comment by hkchu** [comment]
It looks like there are multiple ways a user thread can terminate without bringing down the whole process. Is there any way for LKL to catch all these terminate cases and do the cleanup properly, e.g., to free the associated irq?

At least we need to define APIs for apps to call to free up LKL resources when a thread terminates.

**Comment by opurdila** [comment]
Note: this is fixed by either #160 or #198.

**Comment by Rondom** [comment]
Thanks to #242, the limit is now 4096 (or 1024 on 32bit).

**Comment by liuyuan10** [comment]
Fixed by #246
