### ISSUE TITLE
Is it possible to calling in lkl kernel directly from host thread?

### ISSUE THREAD

**Issue by liuyuan10** [lkl/linux#155]
Now, a lkl syscall needs two thread wakeup to switch from a host thread into syscall thread. This introduces quite huge overhead. For example, my tracing on a benchmark shows lkl_sys_read takes avg 20 us while the syscall thread only takes 3 us to run the real syscall.

I'm thinking if we can make the host thread directly run the syscall. It's easy to have a global scheduling lock shared by lkl kernel and host to block all other kernel threads while host thread is in lkl kernel. And I'll only do it on nonblocking syscalls like read/write on a nonblocking socket.

Is it even possible?

**Comment by opurdila** [comment]
I agree with you, the current system call handling is adding a lot of latency.

I've been trying to find a way around this for some time now but I could not find a way to do it. The main issue is that we can't interrupt a running kernel thread to prevent race conditions with the system call. 

One way to avoid this is to implement a new host environment based on user level threads. That will be useful for other things, like bootloader environments support in LKL.


I will reply with a more extensive explanation of the issues I run as soon as I can, I am currently traveling.

**Comment by thehajime** [comment]
> to implement a new host environment based on user level threads.

FYI.
https://github.com/libos-nuse/lkl-linux/blob/rump-hypcall/tools/lkl/lib/rump-host.c

**Comment by liuyuan10** [comment]
I've been experimenting with letting host thread directly goes into lkl kernel space. I added a global kernel lock and any thread that in lkl kernel space has to hold it. So a host thread can acquire that lock to prevent any lkl kernel thread from running and borrows the task_struct of it's syscall thread. I managed to make it work. hijack on netperf runs without any failure. But I have to hack the kernel code which I believe is not accepted by LKL.

**Comment by thehajime** [comment]
it would be good if we can take a look at the code you've come up with.  

if you see a benefit but not likely to be merged, we can have a branch for an option even though it's hard to maintain.

**Comment by liuyuan10** [comment]
I drafted #160 . Please take a look.

**Comment by liuyuan10** [comment]
Fixed by #246
