### ISSUE TITLE
Segfault on Win32 in wake_up_q (head=0xa8) at kernel/sched/core.c:419

### ISSUE THREAD

**Issue by Rondom** [lkl/linux#156]
Hello,
the attached C-program works fine under Linux x64, but segfaults for me when compiled with the mingw32-toolchain.

    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 2520]
    0x004232bc in wake_up_q (head=0xa8) at kernel/sched/core.c:419
    419		struct wake_q_node *node = head->first;

I am wondering whether I am doing something wrong or whether there is some bug. To make sure there is no issue with different compiler-switches, I am compiling using the same commands that the Makefile would generate for the binaries.

    i686-w64-mingw32-gcc -Iinclude -Wall -g -O2 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -D"BUILD_STR(s)=#s"   -c -o lkl-test.o lkl-test.c
    i686-w64-mingw32-ld -r -o lkl-test-in.o  lkl-test.o
    i686-w64-mingw32-gcc -o lkl-test.exe lkl-test-in.o -llkl -lws2_32 -larchive

C-File: https://gist.github.com/Rondom/2fac4b437002e0d74ea10cf92c63ed73

**Comment by opurdila** [comment]
Hi @Rondom ,

Are you using the patched mingw toolchain? 

You can either compiled them manually (see README.md) or you can use the i686-w64-mingw32-* binaries from tools/lkl/bin/ (just backup you existing files and copy these over). 

I know it is inconvenient, I will try to ping again on the mingw list to try to get those patches merged...

**Comment by Rondom** [comment]
Yes I am using the precompiled binaries.

**Comment by pscollins** [comment]
How are you building LKL? Did you make any changes to any config files?

**Comment by Rondom** [comment]
I am sorry. This was indeed caused by an unclean compile. I was pretty sure I did double-check everything, but it seems I did not... oh well...

I recompiled 844853e from scratch and this specific issue is fixed. Current master has some new issues I will probably find time to investigate and bisect at the end of this week.
