### ISSUE TITLE
Disabling NO_HZ_IDLE offers 50% netperf improvement

### ISSUE THREAD

**Issue by liuyuan10** [lkl/linux#157]
After disabling NO_HZ_IDLE and enabled HZ_PERIODIC, netperf TCP_RR and TCP_STREAM saw 50% improvement on my machine. It makes sense to me, because NO_HZ_IDLE saves energy while CPU is idle but makes each idle loop more expensive.

My question is:
1. Do we want to disable it by default?
2. If so, how to do it? Currently I removed "defconfig" from Makefile and manually edited the local .config.

**Comment by liuyuan10** [comment]
Pls ignore my 2nd question. I find arch/lkl/defconfig.

**Comment by liuyuan10** [comment]
Found it's disabled in commit: 4688ebc04e1fc043ce51ff291041c375b73a4bad. 
Looks like we need a tradeoff between performance and energy. 

Can we make the LKL timer ticks less frequent to save energy? I basically don't know what those ticks are used for. I don't think we need them for scheduling. Because a LKL kernel thread needs to give up the run queue by itself. Timer irq can't preempt a LKL kernel thread AFAIK.

**Comment by thehajime** [comment]
I also see a similar improvement here.

> My question is:
> 1. Do we want to disable it by default?

since it looks like mutual exclusive benefits between two options, I don't think it's good to change.

did you see the part of the code which contributes the expensiveness in NO_HZ_IDLE ? 

if I would elaborate more, it would be a good source of documentation; since the option we're discussing is _NOT_ a general option of Linux kernel but very sensitive one that LKL is interested in.

**Comment by liuyuan10** [comment]
From this [thread](http://unix.stackexchange.com/questions/84947/why-config-no-hz-is-not-set-by-default), it says "CONFIG_NO_HZ(_IDLE) increases the cost of moving into and out of the idle state, slightly increasing the time it takes to get an idle CPU back to work.".

I believe the tick_nohz_idle_enter and tick_nohz_idle_exit in kernel/time/tick-sched.c is expensive though I can't pin point which lines.

Do you know what the timers ticks are used for in LKL? I don't think they are used for scheduling.

**Comment by thehajime** [comment]
> I believe the tick_nohz_idle_enter and tick_nohz_idle_exit in kernel/time/tick-sched.c is expensive though I can't pin point which lines.
> 

I can't pin-point either; quick perf/operf play didn't show those symbols on the output.

> Do you know what the timers ticks are used for in LKL? I don't think they are used for scheduling.

I guess scheduling is completely outsourced to the host-side so, I also think timer ticks are used to update internal variables (jiffies, xtime, etc).

**Comment by opurdila** [comment]
@liuyuan10 I believe this was fixed by #178 and some quick tests on my side seems to confirm this. Please reopen if I am in error.
