### ISSUE TITLE
Sync LKL system clock with host system clock on boot

### ISSUE THREAD

**Issue by Rondom** [lkl/linux#158]
Most Linux systems set the system clock from a hardware clock on boot using hwclock from util-linux.
I am wondering if we can provide this functionality within LKL as well by setting the LKL system clock to the host's system clock.

For many applications the system time inside LKL does not matter, but for lklfuse (and probably also cptofs) it does. Timestamps of files are wrong with the current implementation because the system clock defaults to the unix epoch start if it has not been set explicitly.

**Comment by pscollins** [comment]
I wonder if this is why running `ping` under hijack always complains about going back in time?

**Comment by opurdila** [comment]
Can you please test PR  #159 ? My basic tests seems to work, but please give it a try with your usecase as well.

**Comment by Rondom** [comment]
I tested the patch (see PR-Comment).

Btw, the lkl_ops.time is missing from the docstring in arch/lkl/include/uapi/asm/host_ops.h

**Comment by thehajime** [comment]
> I wonder if this is why running ping under hijack always complains about going back in time?

I guess the following is somehow related; CLOCK_MONOTONIC vs CLOCK_REALTIME.

https://github.com/libos-nuse/linux-libos-tools/issues/16

**Comment by opurdila** [comment]
Fixed by #159
