### ISSUE TITLE
IRQ processing in LKL

### ISSUE THREAD

**Issue by liuyuan10** [lkl/linux#173]
I see LKL IRQs are run when IRQ is re-enabled (arch_local_irq_restore). I see two issues regarding this:

1. IRQ diabling/enabling is common throughout kernel. arch_local_irq_restore in LKL is not cheap due to atomic ops when checking irqs even if no irq is present. This is one key reason I observed that LKL syscalls is slower than real kernel (1us overhead for simple epoll_ctl).

2. I don't know if such a case exists: The LKL kernel is busy doing something (maybe processing rx packets) and no IRQ re-enabling logic is triggered. In such a case no LKL irq can be served. Most importantly, the timer irq is missed (we don't record how many timer irq has been triggered outside LKL). So timers in LKL can be significantly delayed or even dead.

I tried to address 1 in PR#160 where IRQs are only run when idle thread is waken up. But this will make 2 more serious.

I'd like to see if there is a way to not run irqs in arch_local_irq_restore to make syscall fast while doesn't make irq miss more serious.

**Comment by tavip** [comment]
Hi @liuyuan10 ,

Yes, the initial "design" was to try and mitigate 2. with 1. I've also noticed the large overhead in arch_local_irq_restore and I agree we need a better solution.

The main issue behind 2. is that we don't have the means to interrupt (efficiently or portable) an LKL thread so that we can run the irq handlers without the risk of running into race conditions.

BTW, I am not sure that LKL syscalls are slower then native syscalls just because of the atomic operations. I think a much bigger role is that we need to do two context switches: from the native thread to the syscall thread and back.

**Comment by liuyuan10** [comment]
Regarding your BTW, when only counting the time in LKL kernel space, the irq restore becomes the main cost. That's why I'm looking for ways to  get around it on top of PR #160 

If we assume a LKL kernel thread can hold the scheduling slot for a long time, I don't see a better way. And we have to choose to run irqs everywhere (when irq enabled).

If we take one step back and say a LKL kernel thread should always reschedule quickly, then we can choose to run irqs when:

1. In __switch_to
2. exiting syscall
3. in the host thread that triggers the irq like in PR #160

**Comment by liuyuan10** [comment]
After getting more understanding of timekeeping, I think timer irq miss is no longer a big problem. timer irq handler will use lkl clock source to fix time. 

Then I'm more comfortable to skip calling run_irqs in arch_local_irq_restore. This will cause TCP_RR degrade due to delayed irq handling but helps on top of PR #160 . I'll work on it if #160 can make it way to be merged.

**Comment by hkchu** [comment]
Is there more progress on shedding the overhead from arch_local_irq_restore()? I also think the overhead can't be from the atomic operation, but more from "run_irqs()". OTOH if no irq is pending run_irqs() should be cheap so i don't know what happened. It's also strange why the kernel still needs to disable/enable local_irq often - I thought it mostly relies on mutex locks. Even for LKL where SMP is disabled, are there that many critical regions to protect by mucking with local irqs?

In any case moving run_irqs() to __switch_to() seems to be a good idea.

**Comment by liuyuan10** [comment]
This is fixed by #176 

Irq disabling/enabling happens quite a lot from what I see. For example, when spin lock is hold. On UP, spin lock is no op but irq still has to be disabled.

**Comment by opurdila** [comment]
According to the latest comment (and my memory) this should be fixed by #176, so I am going to close the issue. Please reopen if I am wrong.
