### ISSUE TITLE
[RFC / question ] pulling in (some) llvmlinux patches to support clang?

### ISSUE THREAD

**Issue by staalmannen** [lkl/linux#18]
I was thinking that it might be interesting to pull in some patches from llvmlinux to support building lkl with clang? It would make one less makedepend for FreeBSD and other OSes that default to llvm/clang.

http://git.linuxfoundation.org/?p=llvmlinux.git;a=summary

Since many patches are architecture-specific, they are most likely not needed for lkl so some cherry picking could be done.

To keep lkl "clean" (in order to simplify upstreaming), the clang-supported lkl could be maintained in a parallell branch.

Thoughts?
If you think it is interesting/useful I could try to have a go at it this evening.

**Comment by thehajime** [comment]
+1
I have failed a couple of times to build libos/lkl on my macbook. it would be great to play with it in near future.

**Comment by tavip** [comment]
Hi Jens,

Yes, it would be great to have llvm support. I agree that we should keep this as a separate branch and I will create one as soon as you have a pull request for me :)

BTW, the biggest issue I see on Mac OS X is the linker. I've noticed that Max OS X uses a non-gnu linker and LKL requires a full gnu linker in order to be able to use linker scripts for vmlinux.

Thanks,
Tavi

**Comment by staalmannen** [comment]
I have made a pull request. Github complains about some kind of conflict. I don't know if the build tests can be specifically configured for different branches?

In that case, it would be great if that branch got tested with clang

**Comment by thehajime** [comment]
> I have made a pull request. Github complains about some kind of conflict. I don't know if the build tests can be specifically configured for different branches?
> 
> In that case, it would be great if that branch got tested with clang

if you want to change the test behavior on your branch, you can include your change into circle.yml.

https://github.com/lkl/linux/blob/master/circle.yml

**Comment by staalmannen** [comment]
circleci broke again after I updated to the latest master sources. It should work however.

**Comment by thehajime** [comment]
> I just need to fix circleci... annoying to see the red symbol next to the pull request.

i didn't check it but maybe ?
https://github.com/linuxmint/mintsources/issues/47
