### ISSUE TITLE
filesystem specific options

### ISSUE THREAD

**Issue by eu41** [lkl/linux#203]
Just got lklfuse to work in FreeBSD 11.0, but cannot mount btrfs partitions with subvolumes.
Maybe that would be possible if filesystem specific mounting options would be implemented, like subvolid=xxx,discard,autodefrag etc.
Any plans for that?
Thanks,
eu41

**Comment by opurdila** [comment]
@eu41 Can you please try PR #205 and let me know if it works for you? Seems to work with ext4 on my end. Note that you will need to escape , and =, e.g.:

./lklfuse -d -o type=ext4,opts=discard\\,max_batch_time\\=10 system-unsparse.img ~/mnt

**Comment by eu41** [comment]
Tried this and it's not working:

lklfuse -d -o type=btrfs,opts=subvolid\=258\,space_cache\,autodefrag

Fails with message:

Unknown option 'opts=subvolid=258,space_cache,autodefrag'

**Comment by opurdila** [comment]
You need double escapes. Seems that github messed them up, lets try again:

`./lklfuse -d -o type=ext4,opts=discard\\,max_batch_time\\=10 system-unsparse.img ~/mnt
`

**Comment by eu41** [comment]
I reported your answer to the port maintainer in FreeBSD.
Hopefully, he will update the port to the latest in github.
Will let you know as soon as that happens and I try again.
