### ISSUE TITLE
Is it possible to produce a list of files outside arch/lkl that LKL modifies?

### ISSUE THREAD

**Issue by hkchu** [lkl/linux#222]

**Comment by thehajime** [comment]
```
% git diff v4.6-rc5 --stat | grep -vE "arch/lkl|tools/lkl"
 Documentation/lkl.txt                   | 250 +++++++++
 MAINTAINERS                             |   8 +
 Makefile                                |   1 +
 README.md                               |   1 +
 circle.yml                              |  48 ++
 crypto/xor.c                            |   2 +
 fs/xfs/xfs_buf.c                        |  27 +
 include/asm-generic/atomic64.h          |   2 +
 include/asm-generic/vmlinux.lds.h       |   9 +-
 include/linux/compiler-gcc.h            |   4 +
 include/linux/cpu.h                     |   2 +
 include/linux/syscalls.h                |   6 +
 kernel/cpu.c                            |   5 +
 kernel/signal.c                         |   2 +-
 lib/.gitignore                          |   1 +
 lib/raid6/.gitignore                    |   1 +
 lib/raid6/algos.c                       |   9 +-
 scripts/.gitignore                      |   2 +
 scripts/Makefile                        |   2 +
 scripts/basic/.gitignore                |   2 +
 scripts/checkpatch.pl                   |   6 +-
 scripts/kconfig/.gitignore              |   1 +
 scripts/link-vmlinux.sh                 |  12 +-
 scripts/mod/.gitignore                  |   1 +
 tools/Makefile                          |  11 +-
 129 files changed, 13065 insertions(+), 18 deletions(-)
```

**Comment by hkchu** [comment]
Thanks, Hajime! But I don't see any tag newer than v4.3-rc7 on the master branch. How does one identify the commit(s) when LKL is rebased to a newer kernel?

**Comment by Rondom** [comment]
Maybe we someone can push the tags from upstream to make it easier for people.

**Comment by opurdila** [comment]
I've just pushed all the tags up to 4.6-rc5 to the master branch, please let me know if it works for you now.

Something to remember when doing the next merge with upstream kernel :)

**Comment by hkchu** [comment]
Thanks! I just found out merges with the upstream code were documented in pull requests so I can better track things myself. BTW, any plan for those changes in the generic code area (e.g., kernel/cpu.c) before we have a chance to try integrating LKL into the upstream kernel (e.g., Linus tree)?

**Comment by opurdila** [comment]
AFAIR the only problematic change is the cpu_yield_to_irqs() - which is needed to avoid deadlocks for code that uses while (jiffies condition) loops.

I am not sure how we can avoid it without signal support (which we want to avoid since some hosts, e.g. Windows does not support it).
