### ISSUE TITLE
don't call tick_suspend_local when timer is not supported

### ISSUE THREAD

**Issue by M1cha** [lkl/linux#232]
I'm not sure if it's a linux or lkl bug, but when lkl calls tick_suspend_local without setup_irq being called previously the system crashes because the 'tick_suspend_local' doesn't do any pointer checks.

**Comment by tavip** [comment]
I am not sure LKL will be of any use if timers are note supported. Do you have a usecase for that, how did you run into this issue?

**Comment by M1cha** [comment]
I'm porting LKL to UEFI which has no threads.
I'm 'emulating' threads using setcontext/getcontext/swapcontext. that works perfectly with the only limitation being that there is no scheduling from the outside because I can't change the PC from within an interrupt context. To work around this I reschedule when semaphores are used(which happens very often in linux).

I added timer support not and it seems to work :P

**Comment by tavip** [comment]
>I'm porting LKL to UEFI which has no threads.
>I'm 'emulating' threads using setcontext/getcontext/swapcontext.

This is really cool ! I think using user level threads can also with some of the latency issues in some workloads and it would be useful even for posix hosts.

With regard to this issue, it looks like it was resolved, should we close it?

**Comment by M1cha** [comment]
I have to check if I'll run into future problems(e.g. linux waiting for an irq triggered by the timer event while interrupts are disabled), but since I've implemented a (inaccurate) timer the issue is solved, yes

**Comment by M1cha** [comment]
@tavip how is the printk time determined and does it have any effects on the kernel behavior?
I'm calling the scheduler during the timer event now(which is ok since the kernel usually doesn't do any long running tasks except during a syscall in which case it would be ok) but the time always stays the same.

**Comment by tavip** [comment]
@M1cha The printk timestamps are computed based on jiffies, which should get incremented each time the timer irq handler is run.

The behavior you are describing seems to imply that irq handler are not run, if I did not miss anything.

**Comment by M1cha** [comment]
@tavip maybe I misunderstood the functions and implemented them wrong? That's how I understand it:

timer_alloc only allocated internal structures, but doesn't enable a timer
timer_free stops and deletes the timer
timer_set_oneshot runs a timer ONCE after N ns.

is that correct?

**Comment by tavip** [comment]
@M1cha This is correct. The the timer function only schedules the interrupt (it calls lkl_trigger_irq). The actual timer irq handler is called from run_irqs() which is called each time we enable interrupts when they have been disabled. This happens in various places in the kernel code and when we wakeup the idle thread - see arch_cpu_idle()

**Comment by M1cha** [comment]
btw here's my code (sry for the formatting):
https://github.com/efidroid/uefi_apps_LKL/blob/master/UefiHost.c

are there any important libc/libm functions liblkl relies on and which could causes this?
Some may be unimplemented in uefi.

**Comment by M1cha** [comment]
@tavip I fixed this problem:
1) the printk time does use 'time_ns'(not any scheduling based time)
2) I accidentally returned microseconds instead of nanoseconds
3) current_time()*1000000 is not the same as current_time()*1000000ULL

thx :)
