### ISSUE TITLE
dynamic memory size?

### ISSUE THREAD

**Issue by M1cha** [lkl/linux#233]
When using one kernel instance for all devices it's easy to run out of memory and I really don't want to allocate a few hundred MB of data on startup.

**Comment by tavip** [comment]
Can you please clarify? Do you mean device memory (iomem) or kernel memory (the parameter passed to lkl_start_kernel)?

**Comment by M1cha** [comment]
at first I thought it's kernel memory, but apparently I was just running into iomem problems, see #234

**Comment by tavip** [comment]
Ah, OK :) Then I will close this issue. I already have a fix pending for #234 and I will create a PR soon. Please reopen this issue if I misunderstood.
