### ISSUE TITLE
how to increase iomem?

### ISSUE THREAD

**Issue by M1cha** [lkl/linux#234]
```
#define IOMEM_OFFSET_BITS		24
#define IOMEM_ADDR_MARK			0x8000000
#define MAX_IOMEM_REGIONS		(IOMEM_ADDR_MARK >> IOMEM_OFFSET_BITS)
```

how does this work exactly? 8 regions are not enough for what I wanna do(I need up to 60).

**Comment by tavip** [comment]
@M1cha can you please give PR #236 a try and see if it fixes your issues?
