### ISSUE TITLE
build tools/lkl failed

### ISSUE THREAD

**Issue by lamiaaMB** [lkl/linux#253]
I'm building the lkl tools on Ubuntu 15, and I'm getting this error when I use the command 
make -C tools/lkl 

> In file included from include/lkl_host.h:8:0,
>                  from lib/posix-host.c:17:
> include/lkl/asm/host_ops.h:5:1: error: two or more data types in declaration specifiers
>  struct lkl_mutex;
>  ^
> include/lkl/asm/host_ops.h:5:8: warning: useless type name in empty declaration [enabled by default]
>  struct lkl_mutex;
>         ^
> include/lkl/asm/host_ops.h:5:8: error: ‘inline’ in empty declaration

Regards,

**Comment by tavip** [comment]
Hi @lamiaaMB , thanks for reporting this. Can you please paste the last 20-30 lines of the build?

**Comment by lamiaaMB** [comment]
Hi tavip,
I'm sorry for being that late, kindly find below the lines you asked for 

>  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/fcntl.h
  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/poll.h
  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/ioctl.h
  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/fs.h
  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/sembuf.h
  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/ipc.h
  REPLACE	/home/lamiaa/Documents/linux-master/tools/lkl/include/lkl/linux/socket.h
  CC       lklfuse.o
  LD       lklfuse-in.o
  CC       lib/fs.o
lib/fs.c: In function ‘lkl_get_virtio_blkdev’:
lib/fs.c:145:10: warning: ‘device_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  *pdevid = device_id;
          ^
  CC       lib/iomem.o
  CC       lib/net.o
  CC       lib/posix-host.o
In file included from include/lkl_host.h:8:0,
                 from lib/posix-host.c:17:
include/lkl/asm/host_ops.h:5:1: error: two or more data types in declaration specifiers
 struct lkl_mutex;
 ^
include/lkl/asm/host_ops.h:5:8: warning: useless type name in empty declaration [enabled by default]
 struct lkl_mutex;
        ^
include/lkl/asm/host_ops.h:5:8: error: ‘inline’ in empty declaration
cat: lib/.posix-host.o.d: No such file or directory
/home/lamiaa/Documents/linux-master/tools/build/Makefile.build:77: recipe for target 'lib/posix-host.o' failed
make[1]: *** [lib/posix-host.o] Error 1
Makefile:122: recipe for target 'lib/lkl-in.o' failed
make: *** [lib/lkl-in.o] Error 2
make: Leaving directory '/home/lamiaa/Documents/linux-master/tools/lkl'

**Comment by lamiaaMB** [comment]
It looks like you don't support ubuntu versions later that 14

**Comment by thehajime** [comment]
I gave a quick try on my ubuntu  15.04 and 16.04. looks fine both make and make test.
@lamiaaMB could you try to git pull and build again ?

- 15.04
```
root@f0442989e829:~/linux/tools/lkl# lsb_release -a ; gcc --version; git show
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

commit 5b3fcd5876a7ed31ee44f74bb17d8e6bff85700f
Merge: 84f6a9b 1025f3c1
Author: Octavian Purdila <tavi@cs.pub.ro>
Date:   Mon Feb 20 10:42:31 2017 +0200

    Merge pull request #322 from laijs/host_task_stub
    
    use host_task_stub() for host task

```

- 16.04
```
root@zak-docker1:~/lkl/tools/lkl# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@zak-docker1:~/lkl/tools/lkl# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
root@zak-docker1:~/lkl/tools/lkl# git show
commit 84f6a9b4bcb0c17c6c1b5eacccba2f84159b05c4
Merge: 311a4ee 9045528
Author: Octavian Purdila <tavi@cs.pub.ro>
Date:   Thu Feb 16 22:31:46 2017 +0200

    Merge pull request #332 from laijs/lkl/stackoverflow
    
    fix stackoverflow in test_getdents64()
```

**Comment by lamiaaMB** [comment]
I've just tried to pull the latest update ( after the merge of the request ) and I still get the same error. when I tried to build on a remote machine that has ubuntu 14 installed on it , it built fine

**Comment by thehajime** [comment]
please describe a bit more about your environment in order to reproduce this issue.

- ubuntu release (lsb_release -a)
- gcc version
- full build log

did you try to `make mrproper` before your build ?

**Comment by lamiaaMB** [comment]
Ubuntu release : 15.10
gcc version : 4.8
The full build and error logs are attached 
Yes, I tried make mrproper before building and got the same error 

[blog.txt](https://github.com/lkl/linux/files/789696/blog.txt)
[elog.txt](https://github.com/lkl/linux/files/789695/elog.txt)

**Comment by tavip** [comment]
@lamiaaMB could you also please attach an archive of the full tools/lkl directory after the build error?

**Comment by lamiaaMB** [comment]
kindly find it attached 
[lkl.zip](https://github.com/lkl/linux/files/789790/lkl.zip)

**Comment by thehajime** [comment]
> kindly find it attached
> lkl.zip

@lamiaaMB looks like you're not using the latest lkl tree according to the file lkl/lib/posix-host.c in your lkl.zip (mutex_alloc() is at least the old one).

one thing that was my mistake is make mrproper doesn't clean the tools/lkl directory. `make clean -C tools/lkl` instead may help you.

**Comment by thehajime** [comment]
I gave a try with 15.10 ubuntu, almost fresh install and fresh clone of lkl, and can't reproduce the issue you reported.

**Comment by tavip** [comment]
@lamiaaMB can you please run the following command after the build fails (with the /home/tavi/... replaced with your paths)

~/src/linux/tools/lkl$ gcc -Wp,-MD,/home/tavi/src/linux/tools/lkl/lib/.posix-host.o.d,-MT,/home/tavi/src/linux/tools/lkl/lib/posix-host.o -I/home/tavi/src/linux/tools/lkl//include -Iinclude -Wall -g -O2 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fPIC -pthread -DCONFIG_AUTO_LKL_POSIX_HOST -D"BUILD_STR(s)=#s" -D_FILE_OFFSET_BITS=64  -E -o /home/tavi/src/linux/tools/lkl/lib/posix-host.o lib/posix-host.c

and please post /home/tavi/src/linux/tools/lkl/lib/posix-host.o lib/posix-host.c

**Comment by lamiaaMB** [comment]
@thehajime 
I make a new fresh installation and here is the archive after the build failed 

[lkl.zip](https://github.com/lkl/linux/files/792286/lkl.zip)

**Comment by lamiaaMB** [comment]
@tavip 
I ran the command and here are the files :


[posix-host.zip](https://github.com/lkl/linux/files/792289/posix-host.zip)

**Comment by thehajime** [comment]
hmm, still can't reproduce on my 15.10.  changing gcc to 4.7.4 and 4.8.5 from the default one (5.2.1) doesn't help either.

looks like your issue is that a forwarding declartion in host_ops.h (struct lkl_mutex in particular) was interpreted as if an empty declaration with some 'inline' prefix before that.  but I can't find any relevant portion from your posix-host.o so I'm almost lost what's going on.

maybe @tavip will look into this and I hope he find something :)

my ubuntu installation is from docker, then apt-get update;apt-get install various packages. I was wondering how you installed your fresh ubuntu 15.10.

**Comment by tavip** [comment]
@lamiaaMB Thanks. It looks like your  "/usr/include/x86_64-linux-gnu/bits/poll2.h" file is truncated, it ends in the middle of a declaration. Can you please post it here to confirm?

**Comment by lamiaaMB** [comment]
> /* Checking macros for poll functions.
   Copyright (C) 2012-2015 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

#ifndef _SYS_POLL_H
# error "Never include <bits/poll2.h> directly; use <sys/poll.h> instead."
#endif


__BEGIN_DECLS

extern int __REDIRECT (__poll_alias, (struct pollfd *__fds, nfds_t __nfds,
				      int __timeout), poll);
extern int __poll_chk (struct pollfd *__fds, nfds_t __nfds, int __timeout,
		       __SIZE_TYPE__ __fdslen);
extern int __REDIRECT (__poll_chk_warn, (struct pollfd *__fds, nfds_t __nfds,
					 int __timeout, __SIZE_TYPE__ __fdslen),
		       __poll_chk)
  __warnattr ("poll called with fds buffer too small file nfds entries");

__fortify_function int
/*poll (struct pollfd *__fds, nfds_t __nfds, int __timeout)
{
  if (__bos (__fds) != (__SIZE_TYPE__) -1)
    {
      if (! __builtin_constant_p (__nfds))
	return __poll_chk (__fds, __nfds, __timeout, __bos (__fds));
      else if (__bos (__fds) / sizeof (*__fds) < __nfds)
	return __poll_chk_warn (__fds, __nfds, __timeout, __bos (__fds));
    }

  return __poll_alias (__fds, __nfds, __timeout);
}*/


#ifdef __USE_GNU
extern int __REDIRECT (__ppoll_alias, (struct pollfd *__fds, nfds_t __nfds,
				       const struct timespec *__timeout,
				       const __sigset_t *__ss), ppoll);
extern int __ppoll_chk (struct pollfd *__fds, nfds_t __nfds,
			const struct timespec *__timeout,
			const __sigset_t *__ss, __SIZE_TYPE__ __fdslen);
extern int __REDIRECT (__ppoll_chk_warn, (struct pollfd *__fds, nfds_t __nfds,
					  const struct timespec *__timeout,
					  const __sigset_t *__ss,
					  __SIZE_TYPE__ __fdslen),
		       __ppoll_chk)
  __warnattr ("ppoll called with fds buffer too small file nfds entries");

__fortify_function int
ppoll (struct pollfd *__fds, nfds_t __nfds, const struct timespec *__timeout,
       const __sigset_t *__ss)
{
  if (__bos (__fds) != (__SIZE_TYPE__) -1)
    {
      if (! __builtin_constant_p (__nfds))
	return __ppoll_chk (__fds, __nfds, __timeout, __ss, __bos (__fds));
      else if (__bos (__fds) / sizeof (*__fds) < __nfds)
	return __ppoll_chk_warn (__fds, __nfds, __timeout, __ss,
				 __bos (__fds));
    }

  return __ppoll_alias (__fds, __nfds, __timeout, __ss);
}
#endif

__END_DECLS

**Comment by tavip** [comment]
@lamiaaMB OK, the file seems to be intact, but somehow the processing for it ends in the middle of that last definition. Lets try to compile the following simple program:

#include <pthread.h>
#include <stdlib.h>
#include <sys/time.h>
#include <time.h>
#include <signal.h>
#include <assert.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <time.h>
#include <stdint.h>
#include <sys/uio.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <poll.h>

with gcc -c -O2 -o a.o a.c

and see if it fails in which case there is something wrong with the headers/preprocessor/compiler, which is what I suspect at this point. 

Also please run:

gcc -E -O2 -o a.o a.c

and upload a.o

**Comment by lamiaaMB** [comment]
it fails to compile with this error : 
a.c:17:0: error: expected identifier or ‘(’ at end of input

**Comment by lamiaaMB** [comment]
This is the .o file after running the second command 
[a.o.zip](https://github.com/lkl/linux/files/795578/a.o.zip)

**Comment by thehajime** [comment]
now I found in your reported poll2.h (https://github.com/lkl/linux/issues/253#issuecomment-281623547), the poll function is commented out - this may be why you got the compilation error.

I have completely no idea why this is.

```
__fortify_function int
/*poll (struct pollfd __fds, nfds_t __nfds, int __timeout)
{
if (__bos (__fds) != (SIZE_TYPE) -1)
{
if (! __builtin_constant_p (__nfds))
return __poll_chk (__fds, __nfds, __timeout, __bos (__fds));
else if (__bos (__fds) / sizeof (__fds) < __nfds)
return __poll_chk_warn (__fds, __nfds, __timeout, __bos (__fds));
}

return __poll_alias (__fds, __nfds, __timeout);
}*/
```

**Comment by tavip** [comment]
@lamiaaMB @thehajime It looks like your system header file is corrupted, can you try to force reinstall the libc6-dev:amd64 package?

**Comment by lamiaaMB** [comment]
Thank you @tavip ,and @thehajime .
the system headers were, mysteriously, corrupted. After I upgraded the system and reinstalled libc6-dev:amd64, everything worked fine, and I managed to build it successfully. 
Thanks a lot for your support and patience :)
