### ISSUE TITLE
Unable to build in Windows (MSYS2)

### ISSUE THREAD

**Issue by spoiledsport** [lkl/linux#260]
After following the setup instruction for windows, I am unable to build. The build is failing with the following error

make: Entering directory '/e/dev/GitHub/LKL/linux/tools/lkl'
Makefile:77: *** Unrecognized platform: pe-x86-64.  Stop.
make: Leaving directory '/e/dev/GitHub/LKL/linux/tools/lkl'

Any clues?

**Comment by Rondom** [comment]
Build for 32-bit (easiest by using the "MINGW32" shell). See #25

**Comment by tavip** [comment]
Duplicate of #25, closing this issue.
