### ISSUE TITLE
Is LKL usage of setjmp correct?

### ISSUE THREAD

**Issue by liuyuan10** [lkl/linux#266]
As far as I know, setjmp must be used inline so the the stack is still alive when long jmp happens. ["And some esoteric tasks (generally requiring the use of assembly code, such as setjmp and certain kinds of locking) must be performed inline or they won't work right."](https://www.kernel.org/doc/local/inline.html)

But the way we use setjmp in LKL is not inlined so I'm worried this may be cause of segment fault I observed (at very low frequency). I can't explain why it works though.

Also I don't find a way to inline the setjmp into LKL kernel code.

**Comment by tavip** [comment]
Yes, your are right. In the initial implementation I used a different host ops API for setjmp to avoid this issue, but during cleanups I've forgot why I did it that way and scraped it :( I will post a PR to fix this issue soon.
