### ISSUE TITLE
idle thread race condition

### ISSUE THREAD

**Issue by M1cha** [lkl/linux#277]
First off: I managed to use the latest code with my lk user threads(no idea how it just suddenly worked).
I dunno if it's related to my userthreads but I doubt it so here's the log:

```
lkl_idle_tail_schedule: not in idle
[...] WARNING: CPU: 0 PID: 54 at kernel/time/tick-sched.c_1029 0x38da1ddd
```
After that my threading library shows a warning that the system is dead-locked.
The bootstrap/main thread(the external thread which runs syscalls) is in blocking mode, lkl thread called thread_exit and all other lkl threads are in blocking mode too.

This whole situation seems to happen when I run a syscall while another syscall is running(from an interrupt context).

**Comment by liuyuan10** [comment]
If you see "lkl_idle_tail_schedule: not in idle", it means something really bad is happening. Could you check which of (!cpu.idle_pending || !test_bit(TIF_IDLE, &current_thread_info()->flags)) is true? Do you have the stack trace?

**Comment by M1cha** [comment]
@liuyuan10 @tavip I want to let u know that I've finally fixed my setjmp problem. the cause of all that was that my setjmp function didn't have the gcc attribute 'returns_twice'

unfortunately it didn't fix this deadlock problem. I don't see the lkl errors anymore but I still keep ending up in a dead lock(like 5/1 tries).
Can you explain the threading functionality a little bit especially in connection with the (recursive) mutexes and the irq-timer.

While with posix threads the timer gets always called from the thread which created the timer, for my user threads it can be called anytime from any context no matter which thread is currently runnning, can that be a problem?

Also I noticed that the deadlock only happens while the "main" thread is inside the timer interrupt and then waits for a mutex for some reason. Also, when that happens the timer callback is NULL which means that there won't be any further IRQ's.

**Comment by liuyuan10** [comment]
The recursive mutex is needed in such case:
* The kernel thread calls virtio_notify which finally grabs rx virtio queue lock and runs net_rx to receive a packet.
* The same thread triggers a virtio irq to notify the pkt.
* Because we have direct irq now, the same thread runs the irq handler, which may call virtio_notify again and acquire the same rx virtio queue lock.

That's why we need a recursive mutex. Basically it means a mutex can be acquired multiple times by the same thread.

The irq-timer is simple. The timer callback triggers a timer irq and runs the irq handler (because of direct irq), which sets the interval of next timer as well.

I don't understand your word "While with posix threads the timer gets always called from the thread which created the timer". I think there should be a timer thread created to run the callback.

To deal with the deadlock, maybe you can provide a full stack trace of all threads so I can take a look to find out the culprit?

**Comment by M1cha** [comment]
While with posix threads the timer gets always called from the thread which created the timer"
That means that timers are called from an interrupt context. thread_self() dureing  that time will return whatever thread was currently active, which is a different one every time.

"To deal with the deadlock, maybe you can provide a full stack trace of all threads so I can take a look to find out the culprit?"
UEFI doesn't support stack traces for ARM because with thumb code you can't just walk the stack using a frame pointer and need a architecture-specific table and unwind code like c++ exceptions so not even in LKL supports it because it only compiles architecture-independent code.

**Comment by M1cha** [comment]
I'm now using a thread which calls the timer callback instead of calling it directly from  the interrupt context and surprisingly It didn't dead-lock a single time since then so it looks like it's fixed now in case I didn't just make a race condition very rare.

I thought a little more about it and if sth. inside the timer callback waits for the thread which was running when  the interrupt happened it would wait forever because that thread couldn't continue running until the timer callback has returned. Maybe that was the problem?

**Comment by liuyuan10** [comment]
Sound like it was the problem. The timer callback calls lkl_trigger_irq which at least try to acquire cpu.lock mutex. If the timer happen to interrupt a thread that holding that lock, then yes, a deadlock happens.

I think it's a common practise not to have blocking calls in an interrupt context.

**Comment by M1cha** [comment]
I just ran some tests with posix threads in combination with blocking timers and you're right, the threads keep running even when the timer does never return. furthermore when there are no threads(just the default main thread) and the timer is blocking, the main thread can still run and does so with a different pthread_self() pointer even though there's one process only(which I can't explain but I guess it's some libc/pthread safety).

Yes, it probably is common practice in userspace but in minimal environments like bootloaders, timers are usually called within the interrupt context and not from another thread.
