### ISSUE TITLE
Using lkl from C++ fails due to reserved keyword

### ISSUE THREAD

**Issue by petrosagg** [lkl/linux#281]
I'm not sure if using lkl from C++ is in the scope of this project but I do see `#ifdef  __cplusplus` in the header. If it's out of scope please ignore this.

I created a very small test program in C which compiles fine:
```c
#include <lkl.h>
#include <lkl_host.h>

void main() {
	lkl_start_kernel(&lkl_host_ops, 100 * 1024 * 1024, "");
}
```

However, the same simple program in C++ fails because the `struct virtio_net_ctrl_hdr` defined in `linux/virtio_net.h` has a member named `class` which is a reserved keyword in C++.

```c++
extern "C" {
	#include <lkl.h>
	#include <lkl_host.h>
}

int main() {
	lkl_start_kernel(&lkl_host_ops, 100 * 1024 * 1024, "");
}
```

```bash
[petrosagg@satie lkl]$ g++ -Iinclude -llkl -fpermissive -o foo foo.cpp
In file included from include/lkl/asm/syscalls.h:129:0,
                 from include/lkl.h:10,
                 from foo.cpp:2:
include/lkl/linux/virtio_net.h:137:17: error: expected identifier before ‘;’ token
  __lkl__u8 class;
                 ^
include/lkl/linux/virtio_net.h:137:17: error: multiple types in one declaration
[redacted]
```

Adding a `#define class some_unique_identifier` makes it compile but it feels very hacky. Is there a correct way of using lkl from C++?

**Comment by tavip** [comment]
Good catch, we should rename class to something else, PRs welcomed :)
