### ISSUE TITLE
A rump-style fs-utils tool on top of LKL

### ISSUE THREAD

**Issue by copumpkin** [lkl/linux#290]
One of the things I find most exciting about LKL is its potential to enable a much more complete https://github.com/rumpkernel/fs-utils. fs-utils is great, but only supports a limited set of filesystems. It would be great to use LKL to get a similar interface on top of the linux filesystem drivers (ideally including partition support). Is such a project planned or does it already exist? I'm having some trouble figuring out where to start with this project.

**Comment by tavip** [comment]
If I correctly undestand your question, then yes, we already have a tool that can be used to mount via fuse filesystem in userspace, without root access (for Linux): it is called lklfuse and it builds by default. We recently added support for partitions.

If you can't / don't want to use fuse, we have a couple of basic tools to copy from/to filesystem images. See the lkl tools paragraph in the readme.

**Comment by copumpkin** [comment]
Ah yes, `cptofs` looks almost perfect, even supporting the partition stuff. I'll give it a whirl and see if it matches my expectations, thanks!
