### ISSUE TITLE
cpfromfs seems to inject unpredictable prefix into filesystem

### ISSUE THREAD

**Issue by copumpkin** [lkl/linux#295]
I ran the following commands:

```shell
cptofs -P 1 -t ext4 -i test.img ~/linux /
cpfromfs -P 1 -t ext4 -i test.img / ~/linuxcopy
```

Which leads to the following in `~/linuxcopy`:

```
/home/ec2-user/linuxcopy
└── 0000fe01
    ├── linux
    │   ├── arch
...
```

I think that `0000fe01` is an implementation detail of `cptofs` and shouldn't appear in the output. Furthermore I don't think it's constant, so I can't just ask `cpfromfs` to copy starting from that mount point.

**Comment by tavip** [comment]
Good catch, I think we need to issue lkl_sys_chroot to the internal LKL mount point, just like we do in lklfuse.c

**Comment by tavip** [comment]
@copumpkin can you please test #300 ?
