### ISSUE TITLE
Option to skip outermost directory entry in cptofs

### ISSUE THREAD

**Issue by copumpkin** [lkl/linux#297]
Given my last ticket #296, I decided to instead copy my target filesystem into a temporary folder and then bulk `cptofs` from that temporary folder into the root of the target image. Unfortunately, `cptofs` insists (as far as I could tell) on putting the outermost directory in the root. So for example if I create `$TMP/target-root` and then put `bin`, `etc`, and so on into there. Then calling `cptofs ... $TMP/target-root /` will put everything into `/target-root`, which isn't what I want.

**Comment by copumpkin** [comment]
I'm willing to write a PR to fix this but am not sure of how best to do it without changing the general shape of the directory traversal code. Open to suggestions if anyone more familiar with the code can see a trivial fix 😄

**Comment by copumpkin** [comment]
I can see a not-terribly-shitty way to do it by adding a "boolean" to `searchdir` and `do_entry`, and then setting that boolean at the outermost level and not setting it in recursive calls, based on a command-line flag. Still feels a bit hacky though.

**Comment by copumpkin** [comment]
#298 sort of addresses this by letting me write `foo/*` as a source and having the shell take care of doing the outermost expansion

**Comment by tavip** [comment]
@copumpkin I think this is the correct behavior, cp -r does the same.

**Comment by copumpkin** [comment]
@tavip not quite though: if I call `cp -r foo dest` it behaves differently from `cp -r foo/ dest`. The latter skips the outermost entry, whereas the former copies it too.

**Comment by copumpkin** [comment]
Perhaps that's just a darwin thing though? http://serverfault.com/questions/11518/recursive-cp-copies-folder-contents-instead-of-folder-on-os-x

**Comment by tavip** [comment]
> Perhaps that's just a darwin thing though? http://serverfault.com/questions/11518/recursive-cp-copies-folder-contents-instead-of-folder-on-os-x

I think so since on my Linux machine cp -r foo dest and cp -r foo/ dest both copy the folder.

**Comment by copumpkin** [comment]
I see. That's probably more sensible either way. Now that we support multiple source arguments, this issue should be roughly equivalent to using `foo/*` as a source anyway (unless you're copying a massive directory that exceeds the argument limit, which is unlikely), so I'll close for now.
