### ISSUE TITLE
virtio-net ?

### ISSUE THREAD

**Issue by thehajime** [lkl/linux#32]
is there any plans/news to create virtio-net so that networking code with lkl can send/recv packets from outside ?

if not, i'm going to bite a bullet (oops, to have a fun :)).

**Comment by tavip** [comment]
Hi Hajime,

Sorry for the delay in answering, I was traveling last week. I am back now and I have a full week to work on LKL :) NUSE / hijack integration and virtio-net are the first two items on my priority list.

Thanks,
Tavi

**Comment by thehajime** [comment]
@tavip great
