### ISSUE TITLE
0k memory available 

### ISSUE THREAD

**Issue by spoiledsport** [lkl/linux#337]
Guys

Any idea on why I am getting the following message when I run the library

[    0.000000] Memory available: 1008324k/0k RAM

This is in my port to Windows 64bit (LP64). What did I do wrong?

Command and full log

cptofs.exe -p -t ext3 -i sample.img build

[    0.000000] Linux version 4.9.0+ (ediso@DESKTOP-PPLRP4G) (gcc version 6.3.0 (GCC) ) #3 Wed Feb 8 17:01:16 EST 2017
[    0.000000] bootmem address range: 0x6ffc17f1000 - 0x6ffffff0000
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 252499
[    0.000000] Kernel command line:  virtio_mmio.device=292@0x1000000:1
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.000000] Memory available: 1008324k/0k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] lkl: time and timers initialized (irq2)
[    0.000000] pid_max: default: 4096 minimum: 301
[    0.000000] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.000000] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.078000] console [lkl_console0] enabled
[    0.078000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.078000] xor: automatically using best checksumming function   8regs
[    0.078000] NET: Registered protocol family 16
[    0.359000] raid6: int64x1  gen()  4414 MB/s
[    0.625000] raid6: int64x1  xor()  2859 MB/s
[    0.891000] raid6: int64x2  gen()  6516 MB/s
[    1.156000] raid6: int64x2  xor()  4259 MB/s
[    1.422000] raid6: int64x4  gen()  5117 MB/s
[    1.688000] raid6: int64x4  xor()  3886 MB/s
[    1.953000] raid6: int64x8  gen()  5188 MB/s
[    2.219000] raid6: int64x8  xor()  3500 MB/s
[    2.219000] raid6: using algorithm int64x2 gen() 6516 MB/s
[    2.219000] raid6: .... xor() 4259 MB/s, rmw enabled
[    2.219000] raid6: using intx1 recovery algorithm
[    2.219000] clocksource: Switched to clocksource lkl
[    2.219000] NET: Registered protocol family 2
[    2.219000] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    2.219000] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    2.219000] TCP: Hash tables configured (established 8192 bind 8192)
[    2.234000] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    2.234000] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    2.234000] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x1000123, IRQ 1.
[    2.234000] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[    2.234000] SGI XFS with ACLs, security attributes, no debug enabled
[    2.266000] jitterentropy: Initialization failed with host not compliant with requirements: 2
[    2.266000] io scheduler noop registered
[    2.266000] io scheduler deadline registered
[    2.266000] io scheduler cfq registered (default)
[    2.281000] mousedev: PS/2 mouse device common for all mice
[    2.281000] NET: Registered protocol family 10
[    2.281000] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    2.297000] Btrfs loaded, crc32c=crc32c-generic
[    2.297000] Warning: unable to open an initial console.
[    2.297000] This architecture does not have kernel memory protection.
[    2.297000] EXT4-fs (vda): mounting ext3 file system using the ext4 subsystem
[    2.297000] EXT4-fs (vda): mounted filesystem with ordered data mode. Opts:
[    2.313000] reboot: Restarting system

**Comment by levex** [comment]
A simple fix to this would be:

```diff
diff --git a/arch/lkl/mm/bootmem.c b/arch/lkl/mm/bootmem.c
index 6a7966d..923384d 100644
--- a/arch/lkl/mm/bootmem.c
+++ b/arch/lkl/mm/bootmem.c
@@ -7,10 +7,12 @@ static unsigned long _memory_start, mem_size;
 
 void *empty_zero_page;
 
-void __init bootmem_init(unsigned long mem_size)
+void __init bootmem_init(unsigned long mem_sz)
 {
 	unsigned long bootmap_size;
 
+	mem_size = mem_sz;
+
 	_memory_start = (unsigned long)lkl_ops->mem_alloc(mem_size);
 	memory_start = _memory_start;
 	BUG_ON(!memory_start);
```

**Comment by thehajime** [comment]
@levex I think the fix is a right way to do it.  Thanks !

Would you mind if you create a pull request to address this issue ?

**Comment by levex** [comment]
@thehajime Sure, go ahead! You can attach my

`Signed-off-by: Levente Kurusa <levex@linux.com>`
