### ISSUE TITLE
dlsym fail sendmmsg ((null))

### ISSUE THREAD

**Issue by koala0529** [lkl/linux#343]
when i execute this
```
LD_PRELOAD=./liblkl-hijack.so LKL_HIJACK_NET_QDISC="root|fq" LKL_HIJACK_SYSCTL="net.ipv4.tcp_congestion_control=bbr" LKL_HIJACK_NET_IFTYPE=tap LKL_HIJACK_NET_IFPARAMS=tap0 LKL_HIJACK_NET_IP=10.0.0.2 LKL_HIJACK_NET_NETMASK_LEN=24 LKL_HIJACK_NET_GATEWAY=10.0.0.1 haproxy -f ./haproxy.cfg
```
it appear this in my terminal

dlsym fail sendmmsg ((null))
haproxy: lib/hijack/hijack.c:48: resolve_sym: Assertion `0' failed.
Aborted (core dumped)

**Comment by thehajime** [comment]
> dlsym fail sendmmsg ((null))
> haproxy: lib/hijack/hijack.c:48: resolve_sym: Assertion `0' failed.

it apparently says that the standard library on host system doesn't have a symbol `sendmmsg` .
what kind of OS and kernel are you using with this error ?

**Comment by koala0529** [comment]
@thehajime yes,My os is `centos6`,kernel version is `2.6.32`.My glibc version is `2.12`,i think if i update my glibc library to version `2.14`,which can resolve my problem.thank you.
