### ISSUE TITLE
.ro_after_init mapping

### ISSUE THREAD

**Issue by M1cha** [lkl/linux#349]
After enabling memory protection features in UEFI I found out that lkl puts .ro_after_init into .rodata.
This means that lkl tries to write to the rodata section during init - which gives me a MMU permission fault.

Why doesn't this break in the linux userspace? Don't they map .rodata readonly?

**Comment by thehajime** [comment]
I didn't investigate deeply, but it looks like my previous trial may somehow relate to, which disables using the section on mingw32 host (2ac6c7183c22455425a244df1512063ce57dcaf4). 

I didn't quite check how linux userspace doesn't have this issue though..

**Comment by M1cha** [comment]
@thehajime afaik defining RO_AFTER_INIT_DATA to an empty variable implies that you put the section somewhere in your linker script. Since you didn't do that it means that the section should actually not be included in the compiled binary - which obviously sounds even works and makes me wonder how compiles handle that.

**Comment by M1cha** [comment]
ok I've compiled lkl for linux(x64) and this is the related readelf output:
```
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 8] .rodata           PROGBITS         0000000000406000  00405700
       00000000000e5a18  0000000000000000  WA       0     0     256
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)
```

which means that rodata is being mapped as writable. I guess that gcc somehow detects that you're writing to it and decides to map it writable.
After manually removing write-permissions from that section using a hex-editor the binary still runs. Are the section headers being ignored and the program headers used instead?(which would map the whole binary RWE).

**Comment by thehajime** [comment]
@M1cha it would be great if you could check with this fix on UEFI.
