### ISSUE TITLE
OpenSSL with LKL

### ISSUE THREAD

**Issue by speedingdaemon** [lkl/linux#358]
Has anyone tried setting up OpenSSL with LKL linked application?
I have a working application which is using OpenSSL APIs over linux kernel (not LKL) socket APIs.
Now I want to have the same thing with an application that is not using Linux socket APIs but instead LKL APIs.
I have this code:
SSL_set_fd(ssl, fd);
SSL_accept(ssl);

My SSL_accept seems to come back after a SSL_connect initiation from my client application if my server doing SSL_accept is not using LKL APIs.
But SSL_accept seems to block indefinitely if I am using LKL APIs to setup the socket/etc.

So I am assuming that there is some difference in how my fd looks/behaves when returned from accept() vs lkl_sys_accept().

Any thoughts?

**Comment by tavip** [comment]
>SSL_set_fd(ssl, fd);
>SSL_accept(ssl);

That won't work because you need to issue LKL APIs (lkl_sys_read, etc.) instead of the syscalls that SSL uses (regular read, write).

One option would be to use the libhijack, that takes care of hijacking the regular system calls and redirect them to LKL.

**Comment by speedingdaemon** [comment]
Would this alone be sufficient?
LDLIBS := -llkl -llkl-hijack $(LIBS_SSL)

I am getting this error:
./../lkl/linux//tools/lkl//liblkl-hijack.so: undefined reference to `lkl_netdev_vde_create'
./../lkl/linux//tools/lkl//liblkl-hijack.so: undefined reference to `lkl_netdev_dpdk_create'

**Comment by speedingdaemon** [comment]
Actually, will this above approach even work?
I see void __attribute__((constructor(102))) hijack_init(void) defined. 
Do I have to set all those environment variables? If so, then I might not be able to just link to the lkl-hijack library as-is.

**Comment by tavip** [comment]
The way liblkl-hijack is designed is to be loaded via LD_PRELOAD. You can use the bin/lkl-hijack.sh helper script to run binaries to system calls redirected to LKL, e.g.:

```
tools/lkl $ bin/lkl-hihack.sh ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
```
Note that just network system calls are redirected at this point. You will also need to set the varions environment variables to setup the network, see Documentation/lkl.txt

**Comment by speedingdaemon** [comment]
Will liblkl-hijack be able to hijack the system calls in libssl even if my application is already linked to liblkl and is already using lkl_sys_ APIs?

**Comment by speedingdaemon** [comment]
Reason, I ask is that when I do this:
./../../../../../../lkl/linux/tools/lkl/./bin/lkl-hijack.sh ./build/x86/linux/my_lkl_server

I am getting these messages instead of the system actually coming up:
virtio net fd poll: Operation not supported
virtio net fd poll: Operation not supported
virtio net fd poll: Operation not supported
virtio net fd poll: Operation not supported
virtio net fd poll: Operation not supported

**Comment by tavip** [comment]
> Will liblkl-hijack be able to hijack the system calls in libssl even if my application is already linked to liblkl and is already using lkl_sys_ APIs?

Probably not, since the virtio layer issues recv/sendto system calls to the tap interface which will be redirected to LKL if we use libhijack.

Depending on what you want to accomplish, you don't need to link you app with LKL or use LKL APIs when using libhijack. Can you give us more details?

**Comment by speedingdaemon** [comment]
Thanks. I have been able to fix this issue by fixing the BIO layer in OpenSSL to use LKL APIs.
