### ISSUE TITLE
[RFC] Reorganize build system

### ISSUE THREAD

**Issue by tommie-lie** [lkl/linux#36]
I want to use lkl in one of my projects and currently the bulid process is a bit clumsy. There ist no `make install` and the build is only within the tree, and the Kernel's Kbulid won't install lkl headers like `lkl.h` and similar issues that are all minor by themselves.

I therefore want to volunteer to clean up the build system a little bit, provide a sensible install target, provide a .pc file for `pkg-config` and maybe make the featureset of lkl more configurable (e.g. separate the liblkl* stuff from current userspace tools like `lklfuse` and `fs2tar`. 

Before I start, I have two questions:
1. Is this a welcomed thing at all? Or is lkl not intended to be used like e.g. libm or libpthread but only for people who definitely know what they are doing (and do it manually)?
2. Is GNU autotools an acceptable build dependency? I'm most familiar with autotools and I don't feel Kbuild is used too much in tools/ (I think to add config options, these would have to go into arch/lkl?). The only other user of autoconf is tools/usb/usbip, others just use environment variables or Makefile variables that have to be edited.

**Comment by tavip** [comment]
Hi Thomas,

1. It is very welcomed :) 

2. I am not sure about GNU autotools. If there are other users in the Linux kernel tools directory then probably is fine to use it for LKL as well. If not, it will likely get rejected in upstream. 

tools/build might help but I never got the time to fully understand it.

The most mature tool in tools/ is perf so perhaps we should try to use the same approach as it is used there?

Thanks,
Tavi

**Comment by tavip** [comment]
>The only other user of autoconf is tools/usb/usbip, others just use environment variables or Makefile variables that have to be edited.

Sorry, I missed this part of your message. 

In this case autotools seems acceptable to me - and I think it might help in porting LKL to other OSES.

**Comment by tommie-lie** [comment]
i think it increases portability, too. OTOH usbip seems to be rather small tool while lkl has a much larger footprint.
It would definitely be a waste if you could not upstream the patches due to the wrong build system. My concern here is that lkl.o (which is build by Kbuild) is more or less useless without liblkl.o (which would then be build by autoconf). I can imagine people don't like that too much :-/

The other stuff in tools/ is not as "configurable" (as in making good use of a configure script) as I'd like lkl to be.

Not that I know much about the Linux source tree but would it make more sense to move the liblkl stuff into arch/lkl and have lkl.o be the actual library? tools/lkl would then just be the hijack library and the actual tools.

**Comment by tavip** [comment]
>Not that I know much about the Linux source tree but would it make more sense to move the liblkl stuff into arch/lkl and have lkl.o be the actual library? tools/lkl would then just be the hijack library and the actual tools.

That is by design. Arch/lkl stuff it's very Linux specific, requires special linker scripts, CFLAGS/LDFLAGS,  special headers, etc. Stuff in toolks/lkl needs to use host headers, tools and build options.

**Comment by tommie-lie** [comment]
After spending the better part of today reading through your paper, patches and the Kernel build system stuff, I think Kbuild/Kconfig is a better option than autotools. While autotools may have been ported to more platforms, tools/lkl depends on the Kernel Kbuild anyway for lkl.o. I also think that autotools is far less acceptable for such an essential part of the tools. For example, the previously mentioned tools/usb/usbip is not built by make `tools/usb`.
What I have in mind now is something along the lines of `make ARCH=lkl menuconfig && make ARCH=lkl && make ARCH=lkl tools/lkl_install`.

I will start working on this and see how it works out :-)

**Comment by thehajime** [comment]
> I will start working on this and see how it works out :-)

+1
