### ISSUE TITLE
Failed to complie on FreeBSD 11.1

### ISSUE THREAD

**Issue by ccc1924** [lkl/linux#368]
system:freebsd 11.1

error : stat: illegal option -- c

**Comment by thehajime** [comment]
Cc: @cemeyer

**Comment by thehajime** [comment]
using gnustat instead of /usr/bin/stat should eliminate this issue (I installed coreutils and replace gnustat instead stat in scripts/link-vmlinux.sh).
though I still see further errors with the latest LKL on FreeBSD build after this fix.

**Comment by cemeyer** [comment]
Thanks, @thehajime .

**Comment by ddiss** [comment]
I think we can now revert this change. Mainline commit a670b0b4aed1 ("kbuild: Use ls(1) instead of stat(1) to obtain file size") removed all `stat -c` callers.
https://github.com/lkl/linux/issues/539 binary removals will be a bit nicer if we can drop the bin directory altogether.
