### ISSUE TITLE
project web page (basic info)

### ISSUE THREAD

**Issue by thehajime** [lkl/linux#371]
cc: @tavip 

copy pasted from LKL slack channel

I crafted a web page for LKL at https://github.com/thehajime/lkl.github.io
the page only contains a little information, but we can add if you wish

looks like: http://www.iijlab.net/~tazaki/outgoing/test-lkl/
if we can put this repository under github.com/lkl (will be https://github.com/lkl/lkl.github.io), we can publish a web page with http://lkl.github.io

the current contents are very poor: patches wanted !!

**Comment by tavip** [comment]
Looks good to me :)

**Comment by thehajime** [comment]
@tavip 

I don't have sufficient permission to create a repository under github.com/lkl.

**Comment by tavip** [comment]
@thehajime I made you owner, can you please try now?

**Comment by thehajime** [comment]
Thanks, now I can do it.
Here is the new resources for the project.

- repository
https://github.com/lkl/lkl.github.io
- web
https://lkl.github.io/

Slack team is also available.
