### ISSUE TITLE
Version of Linux in LKL

### ISSUE THREAD

**Issue by speedingdaemon** [lkl/linux#373]
Hi All,

Is the LKL having Linux2.6? Or is it something newer?
Any plans on moving to the latest linux version? What is the latest linux version right now, btw?

Thanks

**Comment by Rover-Yu** [comment]
It is based on 4.11 now.

BTW: I tried to rebase it from 4.10 to 4.11 personally, which is not hard.

**Comment by speedingdaemon** [comment]
Ok. Thanks. Do we have a predefined set of steps we need to do to rebase? Please share.

**Comment by tavip** [comment]
We don't do rebases, we do merges and the process is pretty straight forward: just do a merge with upstream, resolve conflicts, build, add new stuff required by upstream and test. For example see #350, #335, #284, #249, #224, etc.

**Comment by speedingdaemon** [comment]
Do you guys have version numbering for LKL? If I pull latest tree, what version would that be?

**Comment by tavip** [comment]
No, we use the version of the kernel we are based on. Right now that is 4.11
