### ISSUE TITLE
build issue?

### ISSUE THREAD

**Issue by speedingdaemon** [lkl/linux#374]
anyone else seen this?
pulled tree just now:
lib/hijack/hijack.c: In function ‘epoll_create’:
lib/hijack/hijack.c:313:9: warning: implicit declaration of function ‘host_epoll_create’ [-Wimplicit-function-declaration]
   res = host_epoll_create(flags);
         ^~~~~~~~~~~~~~~~~
  CC       /lkl/linux/tools/lkl/lib/hijack/init.o
  CC       /lkl/linux/tools/lkl/lib/hijack/xlate.o
  LD       /lkl/linux/tools/lkl/lib/hijack/hijack-in.o
  LINK     /lkl/linux/tools/lkl/liblkl-hijack.so
make: Leaving directory `/lkl/linux/tools/lkl'
-bash-4.2$ pwd
/lkl/linux
-bash-4.2$ grep -r -i host_epoll_create *
Binary file tools/lkl/lib/hijack/hijack.o matches
tools/lkl/lib/hijack/hijack.c:		res = host_epoll_create(flags);
Binary file tools/lkl/lib/hijack/hijack-in.o matches
Binary file tools/lkl/liblkl-hijack.so matches

**Comment by speedingdaemon** [comment]
@tavip any clue?

**Comment by tavip** [comment]
Hmm, that looks like a warning, I'll open a PR with a fix shortly.
