### ISSUE TITLE
system calls in lkl

### ISSUE THREAD

**Issue by speedingdaemon** [lkl/linux#380]
Do we support them? If not, how do we do the equivalent of "ip netns add" in lkl?

**Comment by thehajime** [comment]
could you care to elaborate on what you mean by 'system calls' ?

if you mean you want to execute system calls from outside of the (main) lkl process, then right now we don't have a straightforward way to accomplish it.  a system call proxy (derived from rumpkernel might be the solution if this is the case).

**Comment by speedingdaemon** [comment]
How can I create a namespace and assign an interface to it in lkl?

**Comment by speedingdaemon** [comment]
Basically, the raw netdev interface that we create. How  can I assign it to a namespace in lkl?

**Comment by speedingdaemon** [comment]
By system call, I meant lkl version of system(). So that I could create a namespace in lkl.

**Comment by speedingdaemon** [comment]
@tavip any way to do this in LKL?

**Comment by thehajime** [comment]
current LKL only can host a single process.  no fork/exec support as well as system(3).
so if you wish to create/assign a namespace to a process, you need to do inside the process.

`ifconfig up` or `tc qdisc` etc are implemented in this way.  See tools/lkl/lib/net.c for more detail implementation.

**Comment by Rover-Yu** [comment]
If you wanted to create a network namespace in LKL, you may use netlink API by lkl_syscall() to create them, or as thehajime's suggestions, extending LKL to support syscall proxy sever ;)

Or, if your goal is to run LKL enabled applications under a network namespace in host, that is easy:) just use below command:

```sh
ip netns exec ${NETNS} ${LKL_ENABLED_APP}
```

**Comment by speedingdaemon** [comment]
Yes, I want to do this: "If you wanted to create a network namespace in LKL, you may use netlink API by lkl_syscall() to create them"
Where are the netlink APIs defined?

**Comment by tavip** [comment]
For how netlink is used in LKL see lkl_if_add_ip() in tools/lkl/lib/net.c

**Comment by speedingdaemon** [comment]
Thanks!
