### ISSUE TITLE
The MPTCP subflow is not created for the 2nd interface in LKL+MPTCP scenarios

### ISSUE THREAD

**Issue by mxi1** [lkl/linux#389]
Hi @thehajime, I am using the [libos lkl_mptcp](https://github.com/libos-nuse/lkl-linux/tree/lkl_4.11-mptcp_v0.92) branch you mentioned in issue 384, and I have also merged the patch (motomuman/linux@2c155a8). 

When running LKL_MPTCP-hijacked iperf client instance, there's only one subflow running for the default interface (e.g. eth0). From the captured packets, the packets are MPTCP-enabled, but there's no `ACK+MP_JOIN` packets to create new subflow. 

When digging into the mptcp kernel code, all IPv4 addresses (including lo, eth0, eth1, etc.) are all added into the `mptcp_loc_addr` list; the subflow worker kthread should create subflows for remaining capable routes. However, it doesn't create the subflow. 

When you are verifying the LKL and MPTCP code base, are there any additional configurations for LKL_ environmental variables, so that MPTCP can work as designed? Thanks.

**Comment by brickz** [comment]
I also encountered the same issue.  Based on captured packets, it was also found that LKL_MPTCP-hijacked iperf doesn't announced another address ( eth1 in mix1's description) to peer server.

I tried to find reason using gdb. However, optimized compilation option makes debug kind of difficult. I also wonder how can I disable optimized compilation.

BTW, I have add CFLAGS_mptcp_fullmesh.o = -O0 in net/mptcp/Makefile, but some compilation error happened.

**Comment by thehajime** [comment]
thanks @mxi1 @brickz for the report.
I confirmed the issue and will investigate this soon.

there might be something missing in my branch..

btw, I also made another backport to the following branch: it should contain all the stuffs.

https://github.com/libos-nuse/lkl-linux/tree/lkl_4.13-mptcp_v0.92

**Comment by brickz** [comment]
Thanks, I will try your backport.
For the gdb issue, can you also give me some help?

**Comment by thehajime** [comment]
> For the gdb issue, can you also give me some help?

no idea, sorry.
`-O1` should work but didn't help so much.

**Comment by thehajime** [comment]
The following patch should fix the issue.

```
diff --git a/arch/lkl/Kconfig b/arch/lkl/Kconfig
index 30f6293..00e7876 100644
--- a/arch/lkl/Kconfig
+++ b/arch/lkl/Kconfig
@@ -33,6 +33,8 @@ config LKL
        select IP_ADVANCED_ROUTER
        select IPV6_ADVANCED_ROUTER
        select MPTCP
+       select MPTCP_FULLMESH
+       select MPTCP_PM_ADVANCED
 
 config OUTPUTFORMAT
        string
diff --git a/tools/lkl/lib/hijack/init.c b/tools/lkl/lib/hijack/init.c
index 10b90fe..6c551f8 100644
--- a/tools/lkl/lib/hijack/init.c
+++ b/tools/lkl/lib/hijack/init.c
@@ -549,6 +549,8 @@ hijack_init(void)
 
        if (cfg->sysctls)
                lkl_sysctl_parse_write(cfg->sysctls);
+
+        usleep(500000);
 }
 
 void __attribute__((destructor))
```

The tricky part is a sleep before an application main.
mptcp kernel requires 500 msec after an address addition to reflect their address list managed, hijacked application should start *after* this procedure.

https://github.com/libos-nuse/lkl-linux/blob/lkl_4.13-mptcp_v0.92/net/mptcp/mptcp_fullmesh.c#L1013

I may issue another PR to add a delay at the end of hijack_init().

**Comment by brickz** [comment]
Hajime, I have tried following branch:
https://github.com/libos-nuse/lkl-linux/tree/lkl_4.13-mptcp_v0.92
Still no address announcement happened in LKL_MPTCP-hijacked iperf client side.
I added some printk and found that mptcp_address_worker is not triggered.
If mptcp_address_worker is not triggered, it will be empty in mptcp_local address array. 
If mptcp_local address array is empty, calling mptcp_find_address later in full_mesh_new_session will return -1 either. 
If -1 is returned, local address won't be announced and create_subflow_worker won't be initialized either.

Can you give me some help how to find the reason why the worker is not triggered?

**Comment by thehajime** [comment]
I will update mptcp branches as well with this fix later. 
Reopen this if you still see any issues.

**Comment by thehajime** [comment]
This is my config file for the test.  It looks working fine.

```
{
    "gateway": "10.206.211.1",
    "interfaces": [
        {
            "ifgateway": "100.214.86.129",
            "ip": "100.214.86.168",
            "mac": "02:ab:cd:ef:22:02",
            "masklen": "26",
            "param": "/dev/tap23",
            "type": "macvtap"
        },
        {
            "ifgateway": "10.206.211.1",
            "ip": "10.206.211.253",
            "masklen": "24",
            "mac": "00:0d:ab:cd:4e:97",
            "param": "wlp0s20f0u6",
            "type": "raw"
        }
    ],
    "singlecpu": "1",
    "delay_main": "500000",
    "sysctl": "net.ipv4.tcp_wmem=4096 87380 2147483647;net.mptcp.mptcp_debug=0"
}
```
