### ISSUE TITLE
CONFIG_SLUB_DEBUG_ON=y in arch/lkl/defconfig?

### ISSUE THREAD

**Issue by pscollins** [lkl/linux#39]
Is there a reason for this default? It looks like it causes a hit to performance, and since lkl doesn't make any changes to slub, I can't imagine it would catch many useful bugs.

**Comment by tavip** [comment]
No reason,  just debug leftovers. I will disable it.

**Comment by stfairy** [comment]
Thanks.

FYI I disabled it with

```diff
diff --git a/arch/lkl/defconfig b/arch/lkl/defconfig
index efd3191..06f3a42 100644
--- a/arch/lkl/defconfig
+++ b/arch/lkl/defconfig
@@ -92,4 +92,4 @@ CONFIG_DEBUG_INFO=y
 CONFIG_DEBUG_INFO_REDUCED=y
 # CONFIG_ENABLE_WARN_DEPRECATED is not set
 # CONFIG_ENABLE_MUST_CHECK is not set
-CONFIG_SLUB_DEBUG_ON=y
+# CONFIG_SLUB_DEBUG is not set
```

in my local working directory.
