### ISSUE TITLE
Preserving file times when copying with cptofs

### ISSUE THREAD

**Issue by copumpkin** [lkl/linux#393]
I need all my files inside my image to have a UNIX timestamp of 1. If I just use `cptofs` normally, it uses the current time. I can use `libfaketime` to fool `cptofs` into thinking that the current time is 1, but oddly enough all the timestamps in the image come out as 2 instead of 1.

So now I'm confused what's going on. Can `cptofs` get an option to preserve file times, or if not, does anyone know why all my timestamps are getting incremented by 1 before making it into the image?

If I tell `cptofs` that the time is 0, all my timestamps in the image are 1, so I'm not stuck, but it would be nice if this behaved more intuitively.

cc @dezgeg

**Comment by dezgeg** [comment]
At least for me on current master, the timestamps generated by default are broken (without any use of faketime). On the `circle.yml` in my Git checkout I have:
````
Access: 2017-11-10 17:12:32.780974961 +0200
Modify: 2017-07-18 18:01:35.553271061 +0300
Change: 2017-07-18 18:01:35.553271061 +0300
lstat("circle.yml", {st_dev=makedev(8, 1), st_ino=6132840, st_mode=S_IFREG|0644, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=1959, st_atime=1510326752 /* 2017-11-10T17:12:32.780974961+0200 */, st_atime_nsec=780974961, st_mtime=1500390095 /* 2017-07-18T18:01:35.553271061+0300 */, st_mtime_nsec=553271061, st_ctime=1500390095 /* 2017-07-18T18:01:35.553271061+0300 */, st_ctime_nsec=553271061}) = 0
````

And after I do:
````
./tools/lkl/cptofs -t ext4 -i test.img circle.yml /
````

I end up with this when mounting:
````
Access: 1970-01-05 08:57:04.000000000 +0200
Modify: 1970-01-05 08:57:04.000000000 +0200
Change: 1970-01-05 08:57:04.000000000 +0200
lstat("/mnt/data/circle.yml", {st_dev=makedev(7, 0), st_ino=13, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=4, st_size=1959, st_atime=370496 /* 1970-01-05T08:54:56+0200 */, st_atime_nsec=0, st_mtime=370496 /* 1970-01-05T08:54:56+0200 */, st_mtime_nsec=0, st_ctime=370496 /* 1970-01-05T08:54:56+0200 */, st_ctime_nsec=0}) = 0
````

**Comment by Rondom** [comment]
Yes. We probably need to add a separate host_op for the wall time. The one that is used currently needs to be monotonic. I will have a look.
