### ISSUE TITLE
v6 socket support

### ISSUE THREAD

**Issue by speedingdaemon** [lkl/linux#399]
Hi

Do we have v6 socket support in LKL?
trying to look for lkl_sockaddr_in6 bind/accept APIs.

Getting such errors right now:
error: cannot convert lkl_sockaddr_in6*' to 'lkl_sockaddr*' for argument '2' to 'long int lkl_sys_bind(int, lkl_sockaddr*, int)'

Thanks

**Comment by speedingdaemon** [comment]
Anyone?

**Comment by speedingdaemon** [comment]
@tavip @thehajime

**Comment by thehajime** [comment]
no, you can't use `lkl_sockaddr_in6` in the current version of lkl.

I didn't test it but at least you need to patch like this (additional work may need to have a complete patch).

```
diff --git a/arch/lkl/include/uapi/asm/syscalls.h b/arch/lkl/include/uapi/asm/syscalls.h
index d6e40723b609..dca45ee11424 100644
--- a/arch/lkl/include/uapi/asm/syscalls.h
+++ b/arch/lkl/include/uapi/asm/syscalls.h
@@ -112,6 +112,7 @@ struct sockaddr {
 #define __UAPI_DEF_IP_MREQ     1
 #define __UAPI_DEF_IN_PKTINFO  1
 #define __UAPI_DEF_SOCKADDR_IN 1
+#define __UAPI_DEF_SOCKADDR_IN6        1
 #define __UAPI_DEF_IN_CLASS    1
 #include <linux/in.h>
 #include <linux/in6.h>
```

**Comment by speedingdaemon** [comment]
I see. How much time/effort is needed to get it to work? Will you be able to help here? This is very urgent... In the meantime, I will try to use the above patch and see how far I can get.

**Comment by liuyuan10** [comment]
I've used v6 lkl socket before and it's working. You don't have to have
lkl_sockaddr_in6 to make it work. Just use a the normal sockaddr_in6 and I
think it should work.

sockaddr_storage sock_addr = ....
  int64 ret = lkl_->lkl_sys_bind(socket_fd_,

reinterpret_cast<lkl_sockaddr*>(&sock_addr),
                                 sizeof(sock_addr));

**Comment by thehajime** [comment]
@speedingdaemon maybe if you could give us a minimal example that you want to make it work with ipv6 socket, this should shorten the time/effort to make.  Since v6 socket with hijack library is working (ping6 and netperf as far as I know), this should be not that much.

**Comment by speedingdaemon** [comment]
I am not doing anything fancy. Just want to be able to use these APIs for v6 endpoints:
lkl_sys_connect
lkl_sys_bind
lkl_sys_socket
lkl_sys_listen
lkl_sys_close

**Comment by speedingdaemon** [comment]
any updates?

**Comment by liuyuan10** [comment]
As I said, it should already work. Just try it out. Use standard linux
definition if lkl one is not available.

**Comment by speedingdaemon** [comment]
I just wanted to have the same clean interface instead of having to use the above reinterpret_cast, etc.

**Comment by speedingdaemon** [comment]
@thehajime any updates?

**Comment by speedingdaemon** [comment]
thanks @liuyuan10. your suggestion worked and I have moved on now.
