### ISSUE TITLE
Compilation with dpdk problematic

### ISSUE THREAD

**Issue by octaviansoldea** [lkl/linux#403]
Hello

Following @tavip suggestion, I am opening this issue.

When I try to compile the hijack library in version 9d5deaeaac4b7437d6c39ac2593368e0b052f73f with dpdk I have some problems. In this context, I mention that I am launching "make dpdk=yes" from linux/tools/lkl subdirectory and get errors. Of course, first I am launching ./scripts/dpdk-sdk-build.sh.

In the beginning I see
AUTOCONF /home/octavian/Octavian/DriveNetwork/2017/12December/28/linux/tools/lkl/Makefile.conf
/bin/sh: line 1:  7049 Segmentation fault      (core dumped) make -f Makefile.autoconf -s
and although the compilation continues, it crashes later. 
Please find the complete output in the attachments

[output.txt](https://github.com/lkl/linux/files/1593724/output.txt)

Moreover, please note that I am compiling the hijack library on Fedora 23. This does not happen in version
baf9c8c1843619a7fe6f82e6dbf0d73da86ca106

Best regards,
  @octaviansoldea

**Comment by tavip** [comment]
Thanks for the report. Could you please attach the generated Makefile.conf? Also could you please let me know what make version (make --version) are you using?

**Comment by octaviansoldea** [comment]
Unfortunately, there is no Makefile.conf, I believe make is seg-faulting at the configuration stage. This is the output of 

make --version

[octavian@localhost lkl]$ make --version
GNU Make 4.0
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by thehajime** [comment]
I found the new build script is not correctly running on GNU make 4.0 and 3.8 (installed on Fedora23 and Ubuntu14.04 respectively).  I have a fix and publish soon.
