### ISSUE TITLE
Stale makefile.conf blocks rebuild

### ISSUE THREAD

**Issue by dakami** [lkl/linux#411]
Took me a while to tease this one apart.

If you build lkl, and then clean, and then try to rebuild, it fails.

  CC       /home/ubuntu/linux/tools/lkl/lklfuse.o
In file included from lklfuse.c:14:0:
/home/ubuntu/linux/tools/lkl//include/lkl.h:4:10: fatal error: lkl_autoconf.h: No such file or directory
 #include "lkl_autoconf.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.

This is because Makefile.autoconf creates Makefile.conf and lkl_autoconf.h, but cleaning does not remove Makefile conf which it seems prevents lkl_autoconf.h from being rebuilt.  Removing Makefile.conf restores the ability to build.

**Comment by tavip** [comment]
The idea was that Makefile.conf will record the various parmeters passed (e.g. CROSS_COMPILE, dpdk=yes, etc.) so it would be useful to do a make clean without cleaning the config also. Similar with how regular ./configure and make workflows work in general.

**Comment by thehajime** [comment]
@tavip thanks for the info.

I think my commit https://github.com/lkl/linux/pull/410/commits/6e530cbd8ba8990904ded41c725b4cd4f28a27e6 introduced this issue.  I'm gonna spot the issue and file a PR later.
