### ISSUE TITLE
liblkl_hijack.so vs liblkl-hijack.so? 

### ISSUE THREAD

**Issue by pscollins** [lkl/linux#42]
tools/lib/Makefile provides two targets with slightly different names:

    ifneq (,$(filter $(OUTPUT_FORMAT),elf64-x86-64))
    lib += lib/liblkl_hijack.so
    hijack_objs = $(patsubst %.c,%.o,$(wildcard lib/hijack/*.c))
    objs += $(hijack_objs)
    endif
    
    
    lib/liblkl_hijack.so: LDFLAGS += -ldl
    lib/liblkl_hijack.so: $(hijack_objs) lib/liblkl.a
            $(CC) -o $@ -shared $^  $(LDFLAGS)
    
    # order of -lxxx again really matters for LD_PRELOAD
    lib/liblkl-hijack.so: $(hijack_objs) Makefile lib/liblkl.so
            $(CC) -shared -nodefaultlibs $(lib_objs) -Llib -llkl $(hijack_objs) \
            -ldl -lpthread -lrt -o $@

On my machine, I can't get `liblkl_hijack.so` to work:

    ➜  lib git:(debug) ✗ LD_LIBRARY_PATH=. LD_PRELOAD=liblkl_hijack.so ping localhost
    ERROR: ld.so: object 'liblkl_hijack.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

The rules for `liblkl_hijack.so` don't make sense to me --- why would the hijacking code need to be linked against lkl on some architectures but not others? --- but if they're correct then the conditional should be rewritten to `ifeq (elf64-x86-64,$(OUTPUT_FORMAT))` and the _ version should get a more descriptive name.

My suspicion is that this is a bad copy+paste or something like that --- is there a reason for it that I'm missing?

**Comment by thehajime** [comment]
I think it's accidentally injected during PR/review/merge processes of the original patch.

Originally it was ```liblkl-hijack.so``` is the right target as specified in tools/lkl/bin/lkl-hijack.sh, so I think ```liblkl_hijack.so``` is not intended to be used.

@tavip, let me know if you have any opinion to remove ```liblkl_hijack.so``` is fine or not.

> but if they're correct then the conditional should be rewritten to ifeq (elf64-x86-64,$(OUTPUT_FORMAT)) and the _ version should get a more descriptive name.

I don't understand what you meant by ___the version___. It'd be nice if you elaborate on this more.

**Comment by opurdila** [comment]
>I think it's accidentally injected during PR/review/merge processes of the original patch.
>
>Originally it was liblkl-hijack.so is the right target as specified in tools/lkl/bin/lkl-hijack.sh, so I think liblkl_hijack.so is not intended to be used.
>
>@tavip, let me know if you have any opinion to remove liblkl_hijack.so is fine or not.

Yeah, I messed it up, sorry about that :( We should remove liblkl_hijack.so.

**Comment by pscollins** [comment]
@thehajime I meant "the version containing a _ character, lib_hijack.so." It's all cleared up now, though!

**Comment by thehajime** [comment]
@pscollins got the point. thanks for the clarification.
