### ISSUE TITLE
LKL and newer kernel versions

### ISSUE THREAD

**Issue by sergeay** [lkl/linux#432]
I can see tags up to kernel 4.7.
Are there plans to support newer versions of the kernel?

Thanks,
Serge

**Comment by Rondom** [comment]
LKL is updated semi-regularly. Only the tags are often not pushed to this repo. So adding linus as a remote should give you all the tags (Currently LKL is at 4.15, I think)

**Comment by M1cha** [comment]
@thehajime maybe you should delete all tags to prevent this confusion.

**Comment by thehajime** [comment]
@M1cha thanks for the comment.  +1 (@tavip revert it if you need).

**Comment by thehajime** [comment]
reopen it if you still have issues.
