### ISSUE TITLE
KASAN support?

### ISSUE THREAD

**Issue by jmberg** [lkl/linux#463]
I managed to compile with normal -fsanitize=address, but of course that's not very useful since we have our own allocator and thus nothing will really happen. For KASAN, a few things are required, just wondering if you'd looked at that already.

**Comment by thehajime** [comment]
@jmberg no I personally have never tried. @tavip ?

**Comment by thehajime** [comment]
I found somebody worked on supporting KASAN.

https://taesoo.kim/pubs/2019/xu:janus.pdf

**Comment by jmberg** [comment]
Nope, sorry, I have long given up on LKL for my purposes.

There was another attempt for KASAN in UML, from somebody at Google (and I was a bit trying to help), but that kind of faded out after we couldn't get modules to work properly.

**Comment by bonzobudy225** [comment]
@jmberg thanks for the reply. Well, it's a shame. I have skimmed through the git history of Hydra's LKL repository, and can't see any changes in regard of (k)asan support, even though they told in their research paper that they had added/ported it to work with LKL. Maybe I will email the authors.

**Comment by tavip** [comment]
Fixed by #511
