### ISSUE TITLE
test_nanosleep is flaky under Valgrind

### ISSUE THREAD

**Issue by pscollins** [lkl/linux#48]
Example:

    make -C tests valgrind
    make[1]: Entering directory `~/lkl-linux-master/tools/lkl/tests'
    VALGRIND_CMD="valgrind --suppressions=valgrind.supp --leak-check=full --show-leak-kinds=all" ./boot.sh -t ext4
    20480+0 records in
    20480+0 records out
    20971520 bytes (21 MB) copied, 0.0601454 s, 349 MB/s
    mke2fs 1.42.9 (4-Feb-2014)
    ==51041== Memcheck, a memory error detector
    ==51041== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
    ==51041== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
    ==51041== Command: ./boot -d /tmp/tmp.WW4HVFKxn7 -t ext4 -n lkl_boot
    ==51041== 
    disk_add             passed [3 0]
    netdev_add           passed [0 4 0]
    ==51041== Thread 6:
    ...<snip>...
    ==51041== 
    getpid               passed [1]
    umask                passed [22 777]
    creat                passed [0]
    close                passed [0]
    failopen             passed [-2]
    open                 passed [0]
    write                passed [5]
    lseek                passed [0 ]
    read                 passed [5 test]
    fstat                passed [0 100721 5]
    mkdir                passed [0]
    stat                 passed [0 40721]
    nanosleep            **failed** [97188672]
    mount                passed [0]
    chdir                passed [0]
    opendir              passed [1]
    getdents64           passed [1 lost+found .. . ]
    umount               passed [0 0 0]
    lo_ifup              passed [0]
    netdev_ifup          passed [0 2]
    ==51041== 
    ==51041== HEAP SUMMARY:
    
Presumably because there's an upper bound on the time that passes while the test thread sleeps (under `test_nanosleep` in boot.c):

	clock_gettime(CLOCK_MONOTONIC, &start);
	ret = lkl_sys_nanosleep(&ts, NULL);
	clock_gettime(CLOCK_MONOTONIC, &stop);

	delta = 1e9*(stop.tv_sec - start.tv_sec) +
		(stop.tv_nsec - start.tv_nsec);

	snprintf(str, len, "%ld", delta);

	if (ret == 0 && delta > sleep_ns * 0.9 && delta < sleep_ns * 1.1)
		return 1;

	return 0;

I'm not sure how important you consider this part of the test to be --- is there a very compelling reason to check that `delta < sleep_ns * 1.1`, or can that line be changed to "if (ret == 0 && delta > sleep_ns)" instead?

**Comment by opurdila** [comment]
Good point, I agree that we should remove the upper bound check.
