### ISSUE TITLE
Support for multiple processes

### ISSUE THREAD

**Issue by LHLaurini** [lkl/linux#492]
https://github.com/lkl/linux/blob/1844b34b193086ff9457b3cde119692d5be6a1cb/tools/lkl/lib/posix-host.c#L27-L28

https://github.com/lkl/linux/blob/1844b34b193086ff9457b3cde119692d5be6a1cb/arch/lkl/include/asm/syscalls.h#L11-L12

Right now, the `fork`, `vfork` and `clone` syscalls are not implemented. Is it possible to add support for multiple processes?

**Comment by LHLaurini** [comment]
Answering my own question, I believe that could be possible. We'd need to actually fork the process, which means we'd lose direct access to lkl. So we'd have to use some form of IPC, possibly shared memory and semaphores.

**Comment by tavip** [comment]
Any use-case you have in mind? Fully implementing fork/clone would require MMU support, which we don't currently have.

**Comment by LHLaurini** [comment]
Many programs use fork, like sh, make, some compilers, etc... So not supporting it could limit possible applications.

More specifically, I had intended to use lkl for compiling stuff that needs chroot and mount (like Linux from Scratch) without requiring root.

**Comment by tavip** [comment]
This is not a use-case that we plan to suport with LKL. UML or VMs are better suited for these kind of uses-cases.

**Comment by LHLaurini** [comment]
Indeed, UML fits my use case better.
