### ISSUE TITLE
XFS can't mount: failure at mm/nommu.c:466/vm_map_ram()!

### ISSUE THREAD

**Issue by cemeyer** [lkl/linux#6]
LKL pretends to be a nommu architecture, and the nommu generic code `BUG()`s on `vm_map_ram()`.  (As mentioned in #4.)

**Comment by tavip** [comment]
I think the best way to fix this is to modify XFS to work with nonmmu architectures, even if it will have some performance issues in that configurations (I guess the main issue is memory fragmentation).

This way XFS can support other non-mmu architecture and it also will support LKL environments that don't have mmap (like boot loaders).

What do you think?

**Comment by cemeyer** [comment]
That may be the best way, but I don't know how much work is required.

**Comment by tavip** [comment]
I pushed a patch that implements basic non-mmu support at the cost of memory fragmentation. I'll also send it as a RFC patch to the fs developers to see what they think.

**Comment by cemeyer** [comment]
Interesting.  I am also curious what they think.

**Comment by opurdila** [comment]
Fixed in 8ebe11e77f0c0da90168e4c85f2d4415eb32d8a9
