### ISSUE TITLE
lklfuse utimens incorrectly follows symlinks

### ISSUE THREAD

**Issue by rmmh** [lkl/linux#60]
lklfuse_utimens doesn't call utimensat with the AT_SYMLINK_NOFOLLOW flag.

This makes untar fail if it extracts a symlink before its target and attempts to set the mtime. lklfuse will follow the broken link and return ENOENT.

Upper layers translate utimensat on a symlink to the link or the target depending on the flags before calling utimens on the VFS, which is why FUSE does not receive the flags.

Simple repro that fails in an lklfuse mount:

    ln -s bad link
    touch --no-dereference link

This bug originates in older FUSE examples, and has been fixed:

http://marc.info/?l=fuse-devel&m=130902410132197&w=2
http://unix.stackexchange.com/questions/89886/modify-date-of-symlink-on-bindfs

**Comment by opurdila** [comment]
Fixed in b8b21e562c474b560f841e7764661cd8de260caf, thanks for the detail report @rmmh
