### ISSUE TITLE
netserver hangs under TCP_STREAM test

### ISSUE THREAD

**Issue by pscollins** [lkl/linux#64]
I'm running `netserver` and `netperf` (version 2.7.0, built from the source on netperf's site) as follows:

```
## Server
➜  lkl git:(passive-open) ✗ sudo LKL_HIJACK_NET_TAP=eth0 LKL_HIJACK_NET_IP=192.168.13.2  LKL_HIJACK_NET_NETMASK_LEN=1 LKL_HIJACK_DEBUG=1 taskset -c 10 bin/lkl-hijack.sh netserver -L 192.168.13.2 -d -v 99 -D -f

## Client
➜  lkl git:(passive-open) ✗ netperf -H 192.168.13.2 -t TCP_STREAM -l 1
```

The test runs fine for a while, but it eventually says:

```
[ 3625.088000] virtio_net virtio0: input.0:id 24 is not a head!
```

and hangs forever. `tcpdump` on the interface shows that packets go back and forth normally until LKL stops ack-ing part way through, the sender retries a few times, then starts sending out ARP requests to find out where the host has gone with no response. Looking at it under `gdb` shows that the `netserver` thread is blocked on a `recv` call, and LKL continues to spin up and kill worker threads periodically. `strace` shows that it continues polling the fd associated with the TAP device. `TCP_RR` tests with the same options work fine.

I had to make some changes to the host's routing table to get it to force it not to go through `lo`, the relevant info is:

```
➜  lkl git:(passive-open) ✗ ip addr
2: em1: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    ....
    inet 172.x.y.z/q brd ??.??.??.?? scope global em1
       valid_lft forever preferred_lft forever
861: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 500
    link/ether f2:e4:2a:59:2b:03 brd ff:ff:ff:ff:ff:ff
    inet 192.168.13.1/24 scope global eth0
       valid_lft forever preferred_lft forever
    ...
➜  lkl git:(passive-open) ✗ ip route
...
192.168.13.1 dev eth0  scope link  src 172.x.y.z
192.168.13.2 dev eth0  scope link  src 172.x.y.z 
```

What might be going on here?

**Comment by stfairy** [comment]
Patrick, I noticed that the client side (i.e. netperf) is not run under taskset.

I was able to reproduce virtio_net error reliably without taskset.  So I think it's probably a synchronization issue.

**Comment by pscollins** [comment]
I get the same behavior using the following for the client:

```
➜  lkl git:(passive-open) ✗ taskset -c 11 netperf -H 192.168.13.2 -t TCP_STREAM -l 1
```

Also, I've stuck some print statements to grab syscall numbers from under LKL, and I see the same syscalls are run at the beginning of both of the test types (definitions are in tools/lkl/include/lkl/asm-generic/unistd.h):

```
# TCP_RR
complete_addrinfo using hostname 0.0.0.0 port 0 family AF_INET type SOCK_STREAM prot IPPROTO_TCP flags 01x0
getaddrinfo returned the following for host '0.0.0.0' port '0'  family AF_INET
	cannonical name: '0.0.0.0'
	flags: 22 family: AF_INET: socktype: SOCK_STREAM protocol IPPROTO_TCP addrlen 16
	sa_family: AF_INET sadata: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Got syscall: 198
create_data_socket: socket 514 obtained...
Got syscall: 209
netperf: get_sock_buffer: send socket size determined to be 16384
Got syscall: 209
netperf: get_sock_buffer: receive socket size determined to be 87380
Got syscall: 208
Got syscall: 200
recv_omni: requested recv alignment of 8 offset 0
recv_omni: requested send alignment of 8 offset 0
Got syscall: 201
Got syscall: 204
telling the remote to call me at 40808
Got syscall: 1074
About to start a timer for 5 seconds.
Got syscall: 202
recv_omni: accepted data connection.
Got syscall: 1073 ## recv
Got syscall: 1074 ## send


## TCP_STREAM
complete_addrinfo using hostname 0.0.0.0 port 0 family AF_INET type SOCK_STREAM prot IPPROTO_TCP flags 0x0
getaddrinfo returned the following for host '0.0.0.0' port '0'  family AF_INET
        cannonical name: '0.0.0.0'
        flags: 22 family: AF_INET: socktype: SOCK_STREAM protocol IPPROTO_TCP addrlen 16
        sa_family: AF_INET sadata: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Got syscall: 198
create_data_socket: socket 514 obtained...
Got syscall: 209
netperf: get_sock_buffer: send socket size determined to be 16384
Got syscall: 209
netperf: get_sock_buffer: receive socket size determined to be 87380
Got syscall: 208
Got syscall: 200
recv_omni: requested recv alignment of 8 offset 0
recv_omni: requested send alignment of 8 offset 0
Got syscall: 201
Got syscall: 204
telling the remote to call me at 38199
Got syscall: 1074
About to start a timer for 5 seconds.
Got syscall: 202
recv_omni: accepted data connection.
Got syscall: 1073 ## recv
Got syscall: 1073
Got syscall: 1073
Got syscall: 1073
Got syscall: 1073
Got syscall: 1073
```

so it seems like the state of the LKL kernel in each case is probably similar (I was worried that there might be a syscall that returned an LKL-fd that was passed to a function expecting a host fd, or similar).

I'm not sure how to go about debugging the synchronization issue other than looking through it by hand because I can't get it to run under valgrind, since valgrind executes LD_PRELOAD twice (once for itself, a second time for the library its loaded) so the "outer" LD_PRELOAD grabs `eth0` and the "inner" one fails. Hmmm. I'll see if I can add some quick hack workaround on Monday to only LD_PRELOAD liblkl-hijack.so for the "inner process," maybe that will help track it down.

**Comment by thehajime** [comment]
i'm going to look detail in my machine in my spare time (not likely soon).

**Comment by pscollins** [comment]
I have a fix for this that relies on #74, #75 and #77 --- once those go through I'll send a PR. The issue here is basically that there's a path for threads to enter `virtio_process_queue` via `virtio_write`, which avoids the synchronization in `net_poll`.

**Comment by thehajime** [comment]
great ! I've tried to spot this for a while but didn't get it..
I will review them (and hopefully @opurdila too).

**Comment by pscollins** [comment]
@thehajime Great, thank you!
