### ISSUE TITLE
LKL does not support SMP/reentrant syscalls

### ISSUE THREAD

**Issue by tommie-lie** [lkl/linux#72]
I'm currently writing an application using LKL that waits for data on a network socket using a blocking call to `read()` and occasionally `write()`s data from another application thread. Once the `read()` syscall has been issued, no `write()`s can be performed until the socket receives some data and returns from the `read()`.
While in theory I could use `select()` or `poll()` here because the data I want to write also comes from another socket, I cannot in practice because the other socket is a non-LKL "normal" socket and we cannot mix LKL and non-LKL FDs (yet?).

I digged into the syscall handling and understand that supporting SMP is probably a bigger issue (I also don't fully understand all the internals of LKL's threading yet), but I would like to see support for it (because I have an actual use case for that) and think it should be tracked in an issue :-)

**Comment by opurdila** [comment]
Hi Thomas,

We don't necessarily need full SMP in LKL for this use-case, just the ability to issue multiple (blocking) syscalls. I have something in the backlog, may have it ready in a couple of days.

Thanks,
Tavi.

**Comment by pscollins** [comment]
@tommie-lie Would it be close enough to use nonblocking `read`/`write` and spin in an event loop? You can `read` and `write` to a mixture of LKL fds and host FDs, it's just not allowed to mix them in a single call.

**Comment by tommie-lie** [comment]
@opurdila Sounds great! I already looked into `arch/lkl/kernel/syscall.c` and did not find an _easy_ way to do that without spawning a new kernel thread for each syscall because the call that really blocks is `task_work_run()`. That's why I did not provide a patch in the first place. Let me know if I can be of any help!

@pscollins Yes, that's basically what I'm doing now, but it would be nice if it could be done without busy waiting ;-) Also, I meant we cannot mix the FDs in `select()`/`poll()`, sorry if that was not perfectly clear.

**Comment by phhusson** [comment]
I'm also having this issue, and I'm interestsed in any progress

**Comment by stfairy** [comment]
@opurdila I'm also very interested in this and if there's anything that I can help, please let me know.  Thanks!

**Comment by opurdila** [comment]
It is almost ready I just need to clean it up but due to traveling I did not get a chance to do it. If I don't get a chance to finish it tonight I will push it in a temporary branch so you guys can have a look.

**Comment by opurdila** [comment]
It is almost ready I just need to clean it up but due to traveling I did not get a chance to do it. If I don't get a chance to finish it tonight I will push it in a temporary branch so you guys can have a look.

**Comment by opurdila** [comment]
@tommie-lie can you please take a look at PR #86?

**Comment by tommie-lie** [comment]
On first look, it looks like it could do the trick. I have a deadline to meet next monday, so I can't have a through look at it or experiment with it in my application right now. Sorry :-( But I definitely will try it out next week!

**Comment by phhusson** [comment]
I've tested it, and after a quick test it works for me, thanks !
FIY, my use case is to exchange between lkl's network stack and host network stack, using epoll.

Only thing that you don't mention explicitly, is that lkl_create_syscall_thread must be called without having another blocking syscall running, which might be tricky for some cases. (though it's fine for me)

**Comment by thehajime** [comment]
@phhusson it would be great if you could provide your test case for an additional test of #86.

**Comment by opurdila** [comment]
Fixed in #86
