### ISSUE TITLE
Correct usage of LKL system call API

### ISSUE THREAD

**Issue by cpriebe** [lkl/linux#96]
Hi everyone,

I have a question regarding the correct usage of the LKL system call API. I ran into a problem when running an application linked against musl-libc on top of lkl on my x86_64 system. Using the `stat` system call (via the musl libc wrapper function) "fails", because there is a mismatch between the definition of `struct stat` used in my application code and the one used by lkl. When the results are copied from an instance of `struct kstat` into the user-provided buffer in the function `cp_new_stat`

  https://github.com/lkl/linux/blob/master/fs/stat.c#L229

it uses the following definition of `struct stat`:

  https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/stat.h#L23

However, musl reuses the x86_64-specific definition of `struct stat`:

  http://git.musl-libc.org/cgit/musl/tree/arch/x86_64/bits/stat.h, derived from:
  https://github.com/torvalds/linux/blob/master/arch/x86/include/uapi/asm/stat.h#L82

Now, the problem is that both definitions differ in the order and types of their fields (see `st_mode` and `st_nlink`) which means that dereferencing those fields in my application code will return nonsensical values.

Can anyone tell me what the right way would be to deal with an issue like this?

Thanks!

**Comment by opurdila** [comment]
Hi @cpriebe ,

I don't know how musl, the application and lkl interact, so I may not have a good answer for you.

In general, you should use lkl_ prefixed version for all system calls datatypes. In this case, struct lkl_stat. See test_fstat in tools/lkl/test/boot.c or the other examples in fs2tar.c or lklfuse.c

Thanks,
Tavi

**Comment by opurdila** [comment]
I haven't seen any follow up from some time, closing the issue. Please reopen if more information is required.
